### ISSUE TITLE
Mobile: Native sign-in prompt doesn't show second time if canceled first time (iOS-only?)

### ISSUE THREAD

**Issue by ChrisNZL** [ChrisNZL/Tallowmere2#1023]
Noticed in 0.3.4, iOS.

Flow to reproduce:
1. Ensure user is not signed into Game Center.
2. Launch game.
3. A prompt to sign into Game Center appears.
4. Tap <kbd>Cancel</kbd>.
5. On title screen, attempt to sign in.
6. Game soft-locks / stalls on a "Signing into Game Center" alert with no way to cancel.

### Feedback IDs:
- 20220401-XKBWP
- 20220401-2P227

### TODO:

- [x] Don't prompt user to sign-in during title screen animation.
- [x] Try to ensure native sign-in prompt can show a second time. Might be an issue with [CloudOnce](https://github.com/jizc/CloudOnce).
    - Seems to be an issue with iOS. Sign-in prompt shows if user minimises then re-opens the app.
- [x] Add a cancel button / timeout timer for the "Signing into Game Center" alert.
- [x] Test on Google Play as well.

---

## Further issue
If Game Center is not enabled in their iOS settings, Tallowmere 2 AlertBox shows alert:
>**Unable to Sign In**
>Please check your Internet connection and try again.
- [x] Clarify AlertBox message to "check Internet connection" if device has no Internet; otherwise say to try signing in again.

**Comment by ChrisNZL** [comment]
Fixed / improved in 0.3.4b:

### 1. Sign-in stall fix
Sign-in alert now has a 5-second timeout duration if something stalls; a <kbd>Cancel</kbd> button then appears.

- Handled an iOS-specific bug where the native iOS Game Center sign-in window doesn't appear if canceled once. Appears a second time only if user minimises (or force quits the app) and opens the app again.
 
- For iOS, if the 5-second timeout duration is reached after 2 or more attempts, additional text on the Alert description is added: `If the sign-in window is not working, please try relaunching the game.`

- Clarified error-handling if device has an Internet connection or not.

### 2. AlertBox progress indicator
Added an infinite progress bar to T2's AlertBox for various Alerts when loading or waiting for something to be actioned, such as:
- Connecting to an online co-op game server
- Downloading language strings
- Deleting privacy data
- Signing in
- Signing out
- Submitting game client feedback
- Restoring purchases
- Retrieving online co-op saved games
- Using native purchase UI

### 3. Automatic sign-in prompt disabled upon first launch

To not disrupt the title screen intro, auto sign-in (or prompt to sign in) now only happens if you've signed in before in a previous session.
