### ISSUE TITLE
Mobile: Tasks for launch

### ISSUE THREAD

**Issue by ChrisNZL** [ChrisNZL/Tallowmere2#1025]
### To prepare for mobile launch, tasks still need to happen:

- [x] Localise Google Play achievements
- [x] Localise Google Play leaderboards
- [x] Localise Google Play store text descriptions
- [x] Localise App Store store text descriptions
- [x] Create localised mobile screenshots
- [x] Create localised mobile video previews

### Testers:
- [x] Continue contacting TestFlight testers

- [x] Continue contacting Google Play testers
  - Closed alpha links:
    - https://play.google.com/store/apps/details?id=com.ChrisMcFarland.Tallowmere2 
    - https://play.google.com/apps/testing/com.ChrisMcFarland.Tallowmere2
    
  - Internal link:
    - https://play.google.com/apps/internaltest/4700876795224936909

### Android controllers:
- [x] Add info for [Krom Kloud](https://www.kromgaming.com/en/controllers/kloud)

### Not 100% required, but would like to:
- [x] Translate [tallowmere2.com/android](https://tallowmere2.com/android)

**Comment by ChrisNZL** [comment]
Issues in progress:

- [ ] Android TV: Improve menu navigation when using Android TV Remote.
- [ ] iOS: Allow IAP to be purchased without being signed into Game Center.

**Comment by ChrisNZL** [comment]
Unity In App Purchasing package:

- [ ] Update from 4.1.4 to to 4.4.0

**Comment by ChrisNZL** [comment]
0.3.6 has been approved by Apple today.

Waiting for Google to approve 0.3.6.

### Next steps:

- [ ] Set a public release date.
- [ ] Activate public store pages for pre-registration.

**Comment by ChrisNZL** [comment]
Done. 30 September, 2022.

Mobile releases are rolling out:
- [App Store](https://apps.apple.com/app/tallowmere-2/id1271214084)
- [Google Play](https://play.google.com/store/apps/details?id=com.ChrisMcFarland.Tallowmere2)
