### ISSUE TITLE
Touchscreen: Make menu arrows more "visible"

### ISSUE THREAD

**Issue by ChrisNZL** [ChrisNZL/Tallowmere2#1027]
Currently in 0.3.4, left-side Up/Down arrows are a bit too dark blue / dark teal; they don't stand out nor look like typical arrows.

![image](https://user-images.githubusercontent.com/280814/164802055-8f931839-bc5b-4391-9b03-24a9ce6f2976.png)

### TODO:

- [ ] Make arrows be more "white" to stand out with better contrast.
- [ ] Possibly reshape to look more like traditional arrows.
- [x] Make arrows "blink" initially until user taps them a couple times.

**Comment by ChrisNZL** [comment]
0.3.5: Touchscreen CanvasMenu side arrows now lerp their color to a light blue.

Once tapped / used three times, the lerper stops; assumed the user now knows how to use them.

![t2_touchscreen_arrows_blink](https://user-images.githubusercontent.com/280814/164879160-b1f7b1d2-d362-4fcb-9fa0-738f195bb307.gif)

**Comment by ChrisNZL** [comment]
Reopening this, as there are still reports coming through in the 0.3.6 branch of not knowing that the arrows are arrows.

Perhaps make them white (as tasked above), and an option to toggle their colours.

I feel white is ugly, though white stands out... Could also allow options to style their shape as proper arrows, or retain the currently "fancy" style.

**Comment by ChrisNZL** [comment]
0.3.7d:
- When user taps the bottom pagination text, a tooltip now appears beside the arrows.
  - I hope this will be ample enough to instruct users that the arrows exist.

![image](https://user-images.githubusercontent.com/280814/202580449-f4c4c4c5-9c0c-40c9-bad6-1a94b5c662fc.png)
