### ISSUE TITLE
Touchscreen Buttons: Add options for floating repositioning

### ISSUE THREAD

**Issue by ChrisNZL** [ChrisNZL/Tallowmere2#1029]
Currently in 0.3.4, button configurations are as follows:

- **Movement Buttons** can be repositioned, size changed, opacity changed, symbol type changed.

- **Bottom Buttons** (Chat, Pause, Inventory, Weapon Selector, Quick Swap) have no options.

- **Combat Buttons** (Jump, Shield, Attack) can have their order changed, opacity changed, icon size changed, and pivot position changed.
  - However, can't detach the three buttons from the pivot point.

- **Interact and Quick Heal Buttons** are fixed above the Combat Buttons without much customisation.

### TODO:

- [ ] Make **all buttons** allowed to be circular or square, and repositionable.
- [ ] Allow shortcuts for specific weapons to be positioned anywhere on the screen.

I envision allowing the player to choose a clean slate, then adding all buttons as they see fit: circle sizes, box sizes, tap-and-drag into position.
- Probably prevent buttons from overlapping.
- Allow all buttons to be configured from a config dropdown menu.

Will require a large refactor, but keen to make it happen.

---

The above options will likely be turned into a **Touchscreen Button Configurator (Advanced)** mode.

The existing button scheme will likely be retained as **Touchscreen Button Configurator (Basic)**.

**Comment by ChrisNZL** [comment]
### Further idea / suggestion:
- [ ] Allow Weapon Selector UI to be positioned near its button, rather than centered over the player's character

**Comment by ChrisNZL** [comment]
I really can't be bothered doing this.

Will probably try this out from the get-go in the next game.

Not keen to refactor T2's mobile touchscreen button system at this point. I need to move on.
