### ISSUE TITLE
Mobile: Screen resolution dimensions can be set too small

### ISSUE THREAD

**Issue by ChrisNZL** [ChrisNZL/Tallowmere2#1089]
One bug report from 0.3.6b (feedback ID: `20221003-2ZRGJ`), iPad model `iPad13,4`, is using a screen resolution of 802 × 560, resulting in the UI being too large.

Also have had other comments wishing the UI was smaller – the resolution setting is likely the culprit.

### Tasks:

- [x] Double-check screen resolution choices on mobile, especially for tablets
- [x] Check minimum and maximum screen resolution choices and ranges
- [x] Make bug report data include the minimum and maximum choices (maybe three on each end)

**Comment by ChrisNZL** [comment]
LoadingScene was reducing the screen resolution as intended (just to ensure the kittens and dots are not tiny), but then the MainScene was using the LoadingScene's resolution as the "highest possible resolution" when populating the list of possible screen resolutions.

Fixed now in 0.3.6c – MainScene populates resolutions based upon the startup resolution.
