### ISSUE TITLE
iCloud / Game Center / Google Play / Google Drive / CloudOnce: Syncing issues?

### ISSUE THREAD

**Issue by ChrisNZL** [ChrisNZL/Tallowmere2#1097]
Manual report from iOS, 0.3.6c (feedback ID `20221007-ZQW3R`), across two devices:
- Able to see a deleted saved game on another device.
- Task (achievement) progress not syncing reliably, on startup as well – progress values.

Additional report, feedback ID `0.3.6C_20221011-FMSJG` – no errors or warnings in the log files.

Possible causes:
- Network issues outside of my control
- In-game timing/delay/rate-limit issues
- The current CloudOnce key-value storage type being an issue, which is slated to be revamped anyhow (#1082)

### Tasks:

- [x] See if there are bugs with the in-game rate limiter – _no issues found._
- [x] See if there are startup bugs with the achievement/task progress syncing – ensure the initial sync method is being called properly – _bugs were found; fixed in 0.3.7._
   - This seems to be an issue. 
- [x] Add a menu option to manually force an upload or download of cloud stuff, so player can ensure their account and files are up-to-date (issue #1111) – _added a **Cloud Sync** item action, which syncs everything immediately with a modal Alert._

**Comment by ChrisNZL** [comment]
Further report, 0.3.6c, feedback ID `20221009-NPY7S`

> My weapons progress keeps getting reset!

Log is showing:

```
6:33:41, Frame 816, WARNING »  WARNING: CloudOnce failed to reveal achievement: Native API failed to reveal achievement ReachRoom10_Singleplayer (ReachRoom10_Singleplayer). Cause unknown.
[[[ ^ REPEATING MESSAGE... ]]]

6:33:41, Frame 816, WARNING »  WARNING: CloudOnce failed to reveal achievement: Native API failed to reveal achievement AcquireLoot_Weapon_Rarity4 (AcquireLoot_Weapon_Rarity4). Cause unknown.
[[[ ^ REPEATING MESSAGE... ]]]

6:33:41, Frame 816, WARNING »  WARNING: CloudOnce failed to reveal achievement: Native API failed to reveal achievement AcquireLoot_Shield_Rarity4 (AcquireLoot_Shield_Rarity4). Cause unknown.
[[[ ^ REPEATING MESSAGE... ]]]
```

`Cause unknown.`, reported by CloudOnce, isn't very helpful.

**Comment by ChrisNZL** [comment]
Bugs with the startup Achievement / Progress sync is definitely an issue.

Feedback ID: `0.3.6C_20221017-H8GW3`

Logs do not show any errors or warnings, nor attempts to sync progress from Google Play.

![image](https://user-images.githubusercontent.com/280814/196063844-907e3a05-7258-46d0-9dcf-a3bfccf937c0.png)

![image](https://user-images.githubusercontent.com/280814/196063854-eed7f0d0-3aa3-490d-bc3c-5b332c68107b.png)

**Comment by ChrisNZL** [comment]
0.3.7:

- Fixed startup sync issue for saved games, achievement progress, and account file. Syncing should happen more reliably now (can take a couple seconds after user signs in typically).

- Added a "Cloud Sync" item within the Account tab so player can manually force a sync if desired:

![image](https://user-images.githubusercontent.com/280814/196529163-8b5d8d01-8d6f-4a90-a924-3835b1163818.png)
