### ISSUE TITLE
iOS: Cancelling Game Center login sometimes makes game enter a soft-lock state?

### ISSUE THREAD

**Issue by ChrisNZL** [ChrisNZL/Tallowmere2#1098]
Manual report. 0.3.6c. Feedback ID: `20221006-BGNFM`

> Since I can't connect to the game center, I can't see the achievements or the leaderboard.
> There seems to be a bug where if you select cancel when you can't connect, the screen operations won't work and the game won't progress.
> After restarting the game will be playable

I've sort of experienced this myself... Sometimes the Game Center login flow mid-game gets a bit wonky if the user cancels, then tries to log into Game Center again. Or if the initial prompt makes the user sign in completely, rather than just using their existing account.

Not sure if reliably reproducible, not reliably fixable.

### Tasks:

- [ ] See if Game Center login handling can be improved.

- [ ] Try to ensure no soft locks can occur; ensure the AlertBox's cancel button appears, and is responsive.

- [ ] As a last resort, display a message advising user to quit the game, sign into Game Center _before_ launching the game, then try again.

**Comment by ChrisNZL** [comment]
I don't think this is worth pursuing. Seems to work fine.
