### ISSUE TITLE
MobileStore.ValidateReceipt: Overflow log crashes x2

### ISSUE THREAD

**Issue by ChrisNZL** [ChrisNZL/Tallowmere2#1099]
Auto report, iOS, 0.3.6c, feedback IDs `20221006-QTXFJ`, `20221012-WYP6X`

Overflow Prevention system initiated a Force Quit due to repeated log message(s):

```
4:23:34, Frame 45739, LOG »  Action_SplashBox_ShowPurchaseUI.ExecuteAction: Showing purchase UI...
4:23:34, Frame 45739, LOG »  GameState_UsingNativePurchaseUI: Added to stack.
4:23:35, Frame 45814, LOG »  MobileStore.BeginPurchaseFlow: Purchasing product... product.id: SupporterPack_Core
4:23:45, Frame 45968, LOG »  MobileStore.ProcessPurchase: Processing purchase...

4:23:45, Frame 45968, LOG »  totalPurchases: 0
totalRefunds (and/or cancellations): 0
purchaseIsValidAndCurrent: False

4:23:45, Frame 45968, WARNING »  WARNING: MobileStore.ValidateReceipt: Received receipts, but no matching productID was found.
[[[ ^ REPEATING MESSAGE... ]]]

[[[ ^ REPEATING MESSAGE... ]]]

4:23:47, Frame 46117, LOG »  totalPurchases: 0
totalRefunds (and/or cancellations): 0
purchaseIsValidAndCurrent: False

>>>>> OVERFLOW PREVENTION: REPEATED MESSAGE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

Tallowmere2.MobileStore:ValidateReceiptAndEnsurePurchaseIsCurrent(Product)
Tallowmere2.Platform_CloudOnce:get_UserIsCoreSupporter()
Tallowmere2.CanvasMenu:Update()
```

### Tasks:
- [x] Hash (or add timestamps) to certain log entries regarding IAP messages.
- [x] Investigate and fix why `MobileStore.ValidateReceipt: Received receipts, but no matching productID was found.` is being repeated.
- [x] Handle the `IAPSecurityException` error below as well.

**Comment by ChrisNZL** [comment]
Additional similar crash report on iOS, but for a different error.

Feedback ID: `0.3.6c_20221012-NCGWD`

> WARNING: MobileStore.ValidateReceipt: Receipt is invalid. IAPSecurityException: UnityEngine.Purchasing.Security.GenericValidationException: Cannot validate due to unhandled exception. (System.ArgumentException: Failed to load data.

```
10:50:28, Frame 8396, LOG »  Action_SplashBox_ShowPurchaseUI.ExecuteAction: Showing purchase UI...
10:50:28, Frame 8396, LOG »  GameState_UsingNativePurchaseUI: Added to stack.
10:50:29, Frame 8471, LOG »  MobileStore.BeginPurchaseFlow: Purchasing product... product.id: SupporterPack_Core
10:50:29, Frame 8472, LOG »  MobileStore.ProcessPurchase: Processing purchase...

10:50:29, Frame 8472, WARNING »  WARNING: MobileStore.ValidateReceipt: Receipt is invalid. IAPSecurityException: UnityEngine.Purchasing.Security.GenericValidationException: Cannot validate due to unhandled exception. (System.ArgumentException: Failed to load data.
  at LipingShare.LCLib.Asn1Processor.Asn1Parser.LoadData (System.IO.Stream stream) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.Purchasing.Security.AppleReceiptParser.Parse (System.Byte[] receiptData, UnityEngine.Purchasing.Security.PKCS7& receipt) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.Purchasing.Security.AppleValidator.Validate (System.Byte[] receiptData) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.Purchasing.Security.CrossPlatformValidator.Validate (System.String unityIAPReceipt) [0x00000] in <00000000000000000000000000000000>:0 
  at Tallowmere2.MobileStore.ValidateReceiptAndEnsurePurchaseIsCurrent (UnityEngine.Purchasing.Product unityProduct) [0x00000] in <00000000000000000000000000000000>:0 
  at Tallowmere2.MobileStore.ProcessPurchase (UnityEngine.Purchasing.PurchaseEventArgs unityPurchaseEventArgs) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.Purchasing.PurchasingManager.ProcessPurchaseIfNew (UnityEngine.Purchasing.Product product) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.Purchasing.Extension.UnityUtil.Update () [0x00000] in <00000000000000000000000000000000>:0 )
  at UnityEngine.Purchasing.Security.CrossPlatformValidator.Validate (System.String unityIAPReceipt) [0x00000] in <00000000000000000000000000000000>:0 
  at Tallowmere2.MobileStore.ValidateReceiptAndEnsurePurchaseIsCurrent (UnityEngine.Purchasing.Product unityProduct) [0x00000] in <00000000000000000000000000000000>:0 
  at Tallowmere2.MobileStore.ProcessPurchase (UnityEngine.Purchasing.PurchaseEventArgs unityPurchaseEventArgs) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.Purchasing.PurchasingManager.ProcessPurchaseIfNew (UnityEngine.Purchasing.Product product) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.Purchasing.Extension.UnityUtil.Update () [0x00000] in <00000000000000000000000000000000>:0 

[[[ ^ REPEATING MESSAGE... ]]]
```

```
10:51:02, Frame 9935, WARNING »  WARNING: MobileStore.ValidateReceipt: Receipt is invalid. IAPSecurityException: UnityEngine.Purchasing.Security.GenericValidationException: Cannot validate due to unhandled exception. (System.ArgumentException: Failed to load data.
  at LipingShare.LCLib.Asn1Processor.Asn1Parser.LoadData (System.IO.Stream stream) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.Purchasing.Security.AppleReceiptParser.Parse (System.Byte[] receiptData, UnityEngine.Purchasing.Security.PKCS7& receipt) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.Purchasing.Security.AppleValidator.Validate (System.Byte[] receiptData) [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.Purchasing.Security.CrossPlatformValidator.Validate (System.String unityIAPReceipt) [0x00000] in <00000000000000000000000000000000>:0 
  at Tallowmere2.MobileStore.ValidateReceiptAndEnsurePurchaseIsCurrent (UnityEngine.Purchasing.Product unityProduct) [0x00000] in <00000000000000000000000000000000>:0 
  at Tallowmere2.Platform_CloudOnce.get_UserIsCoreSupporter () [0x00000] in <00000000000000000000000000000000>:0 
  at Tallowmere2.CanvasMenu.Update () [0x00000] in <00000000000000000000000000000000>:0 )
  at UnityEngine.Purchasing.Security.CrossPlatformValidator.Validate (System.String unityIAPReceipt) [0x00000] in <00000000000000000000000000000000>:0 
  at Tallowmere2.MobileStore.ValidateReceiptAndEnsurePurchaseIsCurrent (UnityEngine.Purchasing.Product unityProduct) [0x00000] in <00000000000000000000000000000000>:0 
  at Tallowmere2.Platform_CloudOnce.get_UserIsCoreSupporter () [0x00000] in <00000000000000000000000000000000>:0 
  at Tallowmere2.CanvasMenu.Update () [0x00000] in <00000000000000000000000000000000>:0 

>>>>> OVERFLOW PREVENTION: REPEATED MESSAGE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

Tallowmere2.MobileStore:ValidateReceiptAndEnsurePurchaseIsCurrent(Product)
Tallowmere2.Platform_CloudOnce:get_UserIsCoreSupporter()
Tallowmere2.CanvasMenu:Update()

OUTPUT LOGGER: Previous log event has happened 150 times in a row. Forcing hard quit...
```

**Comment by ChrisNZL** [comment]
Seems that _sometimes_, `unityProduct.hasReceipt` is true even if user has not purchased the product before.

**Comment by ChrisNZL** [comment]
0.3.7:
- Added a `Light` or `Thorough` check-type when performing the `UserIsCoreSupporter` check.
- Created a HashSet for various messages when dealing with the MobileStore, and only logs messages the first time they appear.
- Added an alert if a receipt can't be validated due to a security exception; tells user to try restarting the app.
