### ISSUE TITLE
VAC: Add further details / links to explain player's ban

### ISSUE THREAD

**Issue by ChrisNZL** [ChrisNZL/Tallowmere2#1100]
Confusion for players for why they are "banned" according to their in-game Account tab.

Related feedback ID: `0.3.6B_20221005-BXTV4`

Further feedback ID, `0.3.6B_20221014-G7S7H`

> Buying the game for the first time, installing the game, and trying to connect with a friend, you are prompted to be banned from online because of cheating? Where did I hang up

... Their Steam account has a visible "Game ban" displayed on their profile page from a different game, even if it was issued years ago. I do not want known cheaters from having access to Tallowmere 2's leaderboard system. Need to communicate things better in-game on the Account tab.

### Tasks:

- [x] Add a link advising player to check their VAC status @ https://tallowmere2.com/check-vac-status
- [x] Not all bans are given by _Tallowmere 2_; clarify if their ban was imposed by a different game.
- [ ] Add a EULA to the game to explain that VAC exists and will be enforced.
- [ ] Add text to Disclaimer info on Steam store page listing.

### Related:
- [Feedback System: Add in-game response notifier / message system #430](https://github.com/ChrisNZL/Tallowmere2/issues/430)

**Comment by ChrisNZL** [comment]
0.3.7:
- Clarified text for two ban types:
  - Banned by Tallowmere 2
  - Banned by other game
