### ISSUE TITLE
Loadout: Improve automation / strength detection

### ISSUE THREAD

**Issue by ChrisNZL** [ChrisNZL/Tallowmere2#1101]
Report from 0.3.6c, Android:

> The automatic weapon selection is beyond frustrating. It doesn't seem to work as intended, as it will auto select weapons, very very frequently, that have less strength, less overall damage, that are at a lower level and with less rarity (yes, all at the same time). It doesn't make any sense, and it's aggravating to have to go the load-out everytime to select the previous weapon I was using. I suggest either fix the autoselect, or give us an option to either equip or not a weapon directly when we inspect it in a chest. Having the option to mark it as junk at this stage would be nice as well.

### Tasks:

To look at for all platforms.

When looting a weapon:
- [ ] Provide option to let player manually assign the weapon to a slot
- [ ] Provide option to mark item as junk
- [ ] Provide option to equip immediately

Automation:
- [ ] Double-check the "strength" filter from the Loadout
- [ ] Ensure filters are sorting weapons more desirably

**Comment by ChrisNZL** [comment]
Thoughts for looting from chests:

- **Touchscreen:** Show two buttons: "Acquire & Equip" and "Acquire".

- **Keyboard & Gamepads:** Perhaps handle two actions: Press & Hold to "Acquire & Equip", or just Press to "Acquire".

**Comment by joaompinto** [comment]
The "Acquire & Equip" touchscreen  button sounds perfect to me.
