### ISSUE TITLE
VAC: Add info on Play & Account categories that the game is VAC-enabled

### ISSUE THREAD

**Issue by ChrisNZL** [ChrisNZL/Tallowmere2#1112]
I'd rather not be banning people.

Need to communicate things better that VAC exists.

### Tasks:

- [x] Add text in-game saying VAC exists and will be enforced.
  - Probably create a `Valve Anti-Cheat: ENABLED` or `ENFORCED` item on the Account tab.
- [x] Add a EULA to Steamworks settings, explaining VAC exists and will be enforced.
  - Done: https://store.steampowered.com/eula/655740_eula_0
- [x] Add text to Disclaimer info on Steam store page listing.

**Comment by ChrisNZL** [comment]
0.3.7:
- Added EULA links on Steam website as above.
- In-game, added Valve Anti-Cheat status to the Account tab (either says `ENABLED` or `ENFORCED`).
