### ISSUE TITLE
Add ability to create custom gamepad profiles

### ISSUE THREAD

**Issue by ChrisNZL** [ChrisNZL/Tallowmere2#1116]
While most controllers work, not all do.

Especially related to Android gamepads, as there are many many gamepads out there, and the API to access them is not universal.

### Tasks:

- [x] Allow player to manually map buttons, triggers, and stick directions to a custom controller profile.
- [x] Let profile be detected automatically, or assigned manually.

User would likely need touchscreen or keyboard input to assist with getting the profile created.

Should not be needed on iOS. Just needed on Android and desktop.

**Comment by ChrisNZL** [comment]
Android, PS5 gamepad, report of <kbd>Cross</kbd>/<kbd>Circle</kbd> and <kbd>Square</kbd>/<kbd>Triangle</kbd> buttons being backwards, yet they are correct for me... Wonder if it's a firmware issue.

### As well as custom profiles, perhaps:
- [ ] Add simple option to swap AB/XY (or equivalent) button orders.

### Also with this, might as well:
- [ ] Create an internal Gamepad API, because this feature/refactor will start to get ugly.
- [ ] Implement Steam Input API properly at the same time.

**Comment by ChrisNZL** [comment]
Added in 0.3.7h.

Available on desktop and Android.

Added new category: Options > Input > Custom Gamepads.

Disabled by default.

On Steam, requires Steam Input to be disabled outside of the game., and the selected controller module needs to be InControl Legacy or InControl Native.
