### ISSUE TITLE
Debug Log: ArgumentException: Mesh can not have more than 65000 vertices

### ISSUE THREAD

**Issue by ChrisNZL** [ChrisNZL/Tallowmere2#1119]
Auto report. iOS. 0.3.6c. Feedback ID `0.3.6C_20221020-FG87M`

There's an extremely long string in the player's Debug Log for line starting with `receipt: {"Payload":"` ...

### Tasks:

- [ ] Do not log any mobile `payload` info from the IAP system – this is never handy anyway (transaction IDs are handy, but not payloads).
- [ ] Potentially truncate long strings per log entry to avoid mesh vertex issues.
- [ ] Handle error-catching for the Debug Log if `ArgumentException: Mesh can not have more than 65000 vertices` is called.
   - Should be able to debug / reproduce by logging very long strings.

```
6:00:17, Frame 133565, EXCEPTION »  ArgumentException: Mesh can not have more than 65000 vertices
>>>>> CRITICAL ERROR >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

UnityEngine.UI.VertexHelper.FillMesh (UnityEngine.Mesh mesh)
UnityEngine.UI.Graphic.DoMeshGeneration ()
UnityEngine.UI.Graphic.Rebuild (UnityEngine.UI.CanvasUpdate update)
UnityEngine.UI.CanvasUpdateRegistry.PerformUpdate ()
T2.CanvasMenuItemPanel.UpdateMenuItemAppearances (System.Boolean updateTextOnly)
T2.CanvasMenu.UpdateAppearanceParts (T2.CanvasMenuParts parts, System.Boolean updateTextOnly)
T2.CanvasMenu.LateUpdate ()
UnityEngine.UI.CanvasUpdateRegistry:PerformUpdate()
T2.CanvasMenuItemPanel:UpdateMenuItemAppearances(Boolean)
T2.CanvasMenu:UpdateAppearanceParts(CanvasMenuParts, Boolean)
T2.CanvasMenu:LateUpdate()

GameStates: ShowingTitleScreen, UsingMainMenu
OnlineGameInfo: Device is offline.
No previous server nor online game info.
CanvasMenu.CurrentCategory: AdvancedOptions
SystemPlayer InputDevice: Touchscreen
AccountDisplayName: XXXXX
UserIsCoreSupporter: True
CoreSupporterPack_TransactionIDHash: XXXXX
```

**Comment by ChrisNZL** [comment]
Slight adjustment in 0.3.7a: Removed `receipt` info from being logged.

**Comment by ChrisNZL** [comment]
Additional error, Steam, 0.3.7a, feedback ID `0.3.7a_20221029-347BB`

Log contains a lot of multi-line entries (regarding SQL Leaderboard debugging).

May need to paginate the log, or count number of characters per log entry and restrict the view by that.

Unity does not do a great job of masking / preventing off-screen characters from being rendered when it comes to text.
