### ISSUE TITLE
Online Co-op: Enemy positioning syncing needs improvement

### ISSUE THREAD

**Issue by ChrisNZL** [ChrisNZL/Tallowmere2#1142]
Currently in 0.3.7g, enemies typically receive commands from the server to sync their position when:
- Starting an attack
- Receiving damage
- Landing on the ground

While this is good in theory, it can be visually erratic if positions are slightly different between game clients, and each client is sending slightly different position info for the server to interpret.

### Tasks:

- [ ] Perhaps only sync enemy positions if their position is grossly out of place.
- [ ] Sync positions when enemy moves off-screen.
- [ ] Let positions be a bit more "loose" to slowly "glide" to their desired position, rather than abruptly warping? (though gliding could cause other collision issues, so might be not worth it)
