### ISSUE TITLE
EXCEPTION » [ServicesCore]: System.InvalidOperationException

### ISSUE THREAD

**Issue by ChrisNZL** [ChrisNZL/Tallowmere2#1143]
Some Unity error being thrown on Unity's internal Services plugin (required with the IAP system).

Only happening on Google Play versions. Not very common, but occurs every few days.

Feedback ID: `0.3.7g_20221129-SRTHC`

```
10:41:03, Frame 13348, EXCEPTION »  [ServicesCore]: System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
at System.Collections.Generic.List`1+Enumerator[T].MoveNextRare () [0x00000] in <00000000000000000000000000000000>:0
at System.Collections.Generic.List`1+Enumerator[T].MoveNext () [0x00000] in <00000000000000000000000000000000>:0
at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList (Newtonsoft.Json.JsonWriter writer, System.Collections.IEnumerable values, Newtonsoft.Json.Serialization.JsonArrayContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract collectionContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty) [0x00000] in <00000000000000000000000000000000>:0
at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject (Newtonsoft.Json.JsonWriter writer, System.Object value, Newtonsoft.Json.Serialization.JsonObjectContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract collectionContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty) [0x00000] in <00000000000000000000000000000000>:0
at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject (Newtonsoft.Json.JsonWriter writer, System.Object value, Newtonsoft.Json.Serialization.JsonObjectContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract collectionContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty) [0x00000] in <00000000000000000000000000000000>:0
at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize (Newtonsoft.Json.JsonWriter jsonWriter, System.Object value, System.Type objectType) [0x00000] in <00000000000000000000000000000000>:0
at Newtonsoft.Json.JsonSerializer.SerializeInternal (Newtonsoft.Json.JsonWriter jsonWriter, System.Object value, System.Type objectType) [0x00000] in <00000000000000000000000000000000>:0
at Newtonsoft.Json.JsonConvert.SerializeObjectInternal (System.Object value, System.Type type, Newtonsoft.Json.JsonSerializer jsonSerializer) [0x00000] in <00000000000000000000000000000000>:0
at Unity.Services.Core.Telemetry.Internal.FileCachePersister`1[TPayload].Persist (Unity.Services.Core.Telemetry.Internal.CachedPayload`1[TPayload] cache) [0x00000] in <00000000000000000000000000000000>:0
at Unity.Services.Core.Scheduler.Internal.ActionScheduler.ExecuteExpiredActions () [0x00000] in <00000000000000000000000000000000>:0
>>>>> CRITICAL ERROR >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

Unity.Services.Core.Scheduler.Internal.ActionScheduler:ExecuteExpiredActions()
```

**Comment by ChrisNZL** [comment]
0.4:
- Suppressed as a warning.

**Comment by ChrisNZL** [comment]
### Tasks:

- [ ] Update Unity Services Core to 1.7.0.
- [ ] Update Unity In App Purchasing to 4.5.2.
- [ ] Test mobile clients.

**Comment by ChrisNZL** [comment]
Should be fixed in 0.3.7h.

Related: issue #1148
