### ISSUE TITLE
CloudOnce: "Play" categories are not being dirtied when game receives data from cloud

### ISSUE THREAD

**Issue by ChrisNZL** [ChrisNZL/Tallowmere2#1160]
Able to reproduce a bug on Google Play. Seems to have been reported a lot in 0.3.7g.

### Seems to be reproducible in the following manner:
- Sign into Google Play. Create a game. Change character, equip a new weapon. Save game. 
- Quit app completely.
- Start app again. Click the "Play" button. Saved game exists.

But then:
- Uninstall the game.
- Install the game.
- Sign into Google Play. Click the "Play" button. Saved game does not exist. Only appears if you force quit the app, then load the app a second time.

---

From my own logging (feedback ID `0.3.7i_20230102-6RQLM`), and looking at code, I believe I am not dirtying enough "Play" categories when receiving data from the cloud. The game's FileSystem assumes data is readily available and up-to-date at the start, but this is not so.

### Files/methods to investigate:
- `Platform_CloudOnce.CloudOnce_OnCloudLoadComplete`
- `Platform_CloudOnce.CloudOnce_OnNewCloudValues`
- `CustomFileManager_CloudOnce.LoadFilesFromCloud`

### Tasks:
- [ ] Dirty the "Play" category, `game.category_play_load.isDirty = true;`
- [ ] Ensure game parses latest saved game data when `CloudOnce_OnCloudLoadComplete` and/or `CloudOnce_OnNewCloudValues` are called
   - [ ] Add entries into the game's FileSystem

**Comment by ChrisNZL** [comment]
Fixed in 0.3.7j.

Main culprits resolved:
- Game now refreshes its saved games and achievement data on the CloudOnce `OnNewCloudValues` event (which was the main issue).
- Game's FileSystem now imports local files after signing out.
- Game now refreshes its achievement progress list properly when signing in or out.
