### ISSUE TITLE
Online Co-op: Double-check health / damage / slay flow + incorrect HUD health numbers

### ISSUE THREAD

**Issue by ChrisNZL** [ChrisNZL/Tallowmere2#477]
Reported in 0.1.3, possibly related to issue #476 ...

Client player has health, yet server thinks client player has received enough damage to die..?

To check:
- Double-check max health numbers mismatching between client and server (related to Demon Statue rewards, item rewards, potion buffs, potion permanent rewards, kitten blessings)

- Check healing is not disrupting flow of health calculation potions, hearts, health regen)

**Comment by ChrisNZL** [comment]
Related:
- Reports from 0.1.8 / 0.1.8a saying:
    - Damage from traps is way too high
    - Damage from traps might not be adhering to pain limits

Related issues to investigate:
- [Enemies & Traps: Damage scales too high late-game? #461](https://github.com/ChrisNZL/Tallowmere2/issues/461)
- [Core Attributes: Double-check Pain Limit calculation #474](https://github.com/ChrisNZL/Tallowmere2/issues/474)

**Comment by ChrisNZL** [comment]
Further comments:

> In Coop Mode, when players go deeper in the dungeon, if they have been kicked offline once, the damage of trap will become super high. But if their partner has never been kicked offline, the damage of trap remains "1".

**Comment by ChrisNZL** [comment]
Likely related:
- [Online Co-op: Client-side health not updating when acquiring shield #901](https://github.com/ChrisNZL/Tallowmere2/issues/901)

**Comment by ChrisNZL** [comment]
## Online bug regarding health, not syncing to client properly

As of version 0.2.8a, definitely a bug with health not updating on the client properly sometimes. Server maintains each creature's max health as the authority, but there are inconsistencies on the client.

### Related classes and methods:
- `NetworkMessage_MakeCreatureDrinkPotion`
- `NetworkMessage_SyncCreatureHealth`
- `SimpleItemStruct.ConsumeVessel`
- `VesselExtension.OnConsumedByCreatureStruct`
- `CreatureStruct.SetHealthFromServer`
- `NetworkMessage_InteractWithDungeonRoomObject`
- `CreatureStruct.AcquireOrEquipInventoryItemStruct`

### Damage calculations
Damage is calculated client-side, then sent to the server.
- `CreatureStruct.ReceiveDamage` factors in `CreatureStruct.alterantTracker.IncomingDamageLimit`

  - HOWEVER, `IncomingDamageLimit` uses `alterantTracker.maxHealth` directly rather than `CreatureStruct.MaxHealth`.

    - When playing online, `CreatureStruct.MaxHealth` returns `CreatureStruct.maxHealth_fromServer` rather than `CeatureStruct.alterantTracker.maxHealth`.

    - [ ] **To try:** Make `AlterantTracker.IncomingDamageLimit` use `CreatureStruct.MaxHealth`

### Health HUD and numbers
- [ ] Make `CreatureStruct._SetCurrentHealthFromServerAndResetTimer` **_always_** update the creature's HUD

Code goes like:
```csharp
if (maxHealth_fromServer > 0 && this.CurrentHealth != currentHealth_fromServer) {
	this.CurrentHealth = currentHealth_fromServer;
	bool splashBlood = false;
	this.HUD?.SetHealth(creature, splashBlood);
}
```
  - Need to always update the HUD.
    - Related: [Online Co-op: Client-side health not updating when acquiring shield #901](https://github.com/ChrisNZL/Tallowmere2/issues/901)
    - Believe one inconsistency is the player's current health can change when equipping a shield (before waiting for server to send the message to acknowledge the new shield has been equipped and health potentially has changed), but HUD does not update due to local max health already equalling max health reported by server.
    - [ ] Server-side, debug to ensure max health is updated appropriately, and that client is receiving the proper value too.

- [ ] When debugging, expose all number-related fields and properties:
  - `CreatureStruct._currentHealth`
  - `CreatureStruct.currentHealth_fromServer`
  - `CreatureStruct.maxHealth_fromServer`

### Todo for investigation:
Implement extra logging / debugging on servers:
- [ ] Kitten blessings
- [ ] Pedestal offerings
- [ ] Demon Statue rewards
- [ ] Potion permanent upgrades

**Comment by ChrisNZL** [comment]
Merging #823 into this issue.

### To log and check:
- [ ] Trap damage, as reported by server, and verify what the damage is when a client disconnects and reconnects.
- [ ] Verify creature stats sync correctly when reconnecting.

> Further feedback – v0.2.4 – feedback ID: 20210313-BCB9C:
>
> 每次重连游戏后 防御属性不正常 原来掉1点血的会变成伤害很高的血量
> Every time the game is reconnected, the defensive attribute is abnormal. The original one that loses 1 point of blood will become a high damage blood volume.

**Comment by ChrisNZL** [comment]
## Potions: Issue identified, and fixed now in 0.2.9

A few days ago, [I posted on T2's Steam forum about potion issues](https://steamcommunity.com/app/655740/discussions/0/2990917484141905590/?tscn=1630824576#c3039355912923445024):

> Currently in version 0.2.8a:
> 
> • When a client consumes a potion, the client is immediately rewarded with the potion's effects first, then tells the server second, without waiting for the server to respond. This is by design (for now).
> 
> • However, I've identified a bug where the order of events that gets sent to the server is incorrect. The client decreases the potion's quantity by one, then tells the server to set the quantity, and then tells the server to finally consume the potion.
> 
> • This order of events is incorrect, as the server can potentially set the potion's quantity to zero, and then the server can't drink the potion because it no longer exists. If the potion's initial quantity was 2 or higher, then the potion is consumed properly, and its effects are rewarded server-side as intended. So, I will be fixing to ensure the order of events are corrected.
> 
> • Another bug I've discovered, is that server-side, the server is just grabbing the first available potion in the player's inventory and consuming it, rather than getting the appropriate potion. So things work fine if you only have one type of potion and its quantity is 2 or higher, but otherwise, inconsistencies start to happen.

This is now fixed in 0.2.9.

Investigation and refactor notes:
- Potions use the game's `SimpleItemStruct` class, which originally was intended for simple items that use a quantity, such as basic potions and upcoming collectable items, with each item using a basic `InventoryItemID`. The intent was that each creature would only ever hold one class of each simple item type, and its quantity would be adjusted.
- At some point, as more potion types were added, I diverged _all_ potions into using the same `InventoryItemID`, but optionally having a `VesselExtensionID` attached to them for fancier potions that grant buffs or effects, as well as adding a `VesselIntensity` value.
- When a client drank a potion, the client would tell the server that it was consuming the potion, but only sending its `InventoryItemID`, which is the same for all potions. The server would then find the first potion that matched, which could be _any_ potion in the player's inventory – oops.

Network messages have been cleaned up now:
- Now in 0.2.9, the client tells the server which uniquely-assigned `NetID` the potion uses, which is concise for the particular potion being consumed (a `NetID` is what the game uses to identify weapons, shields, creatures, chests, etc).
- Two network messages have been removed: `SetSimpleItemQuantity` and `RemoveItemFromInventory`.
- The network message `MakeCreatureDrinkPotion` now properly handles item quantity change, and removes the potion from the creature's inventory and dungeon's database if the quantity is zero.
- `MakeCreatureDrinkPotion` is also now more robust, instructing other clients to execute the potion's effect for the creature (if any), making said creature performing their drinking animation (if possible), reducing the potion's quantity, and removing the potion from the dungeon's database if needed.

**Comment by ChrisNZL** [comment]
## Health sync: Issue identified when creating a new game, or rejoining/reconnecting to a game. Fixed in 0.2.9.

Fixed various damage calculations with client not always using the proper uint for max health when playing online.

Also identified issue where players' max health, as held by the server, was not sent to the client until the client took damage, healed, or adjusted their max health through other means.
- Server now sends a message to sync the player's health immediately when connected to a server, so calculations and numbers should be fixed now in 0.2.9.

**Comment by ChrisNZL** [comment]
## Enemy and trap damage sync: Issue identified where server was not sending enemy/trap level-up info when "Dungeon grows stronger" intermission was displayed. Fixed in 0.2.9.

Internally, enemy damage is roughly calculated using two main portions:
1. A basic damage number based on the room number, and
2. A sum of a random 1-3 value called `EnemyLevelUpResult` that is randomly chosen when the "Dungeon grows stronger" intermission is displayed.
    - So in version 0.2, on average, enemies gain +2 damage for each `EnemyLevelUpResult`... which is why some runs feel harder or easier than others; the number is different for each enemy, and it changes each run.

At one point in time many versions ago, the server would just set the enemy's damage as a single number and send it to the clients.

During a refactor, however, said damage number was deprecated, and replaced with an @ runtime calculation that calculated all EnemyLevelUpResults to produce the final number dynamically, rather than being hard-set, eg never written to disk.

It seems the server never actually sent these results to the clients during a session. The results would only get set if the client disconnected and reconnected.

So, enemies and traps would feel like they were forever weak, only dealing one or two damage, unless the client disconnected and reconnected.

So, players would feel brittle and weaker after reconnecting because the server was then finally sending the proper info, which would make the enemies feel harder... Which is how it's supposed to feel.

This is fixed now in 0.2.9. Server sends proper info as intended.

Which means online now feels harder in 0.2. Number overhauls are still planned for 0.3 with a new Ruleset in the works.

**Comment by ChrisNZL** [comment]
Closing this now. Many issues fixed for 0.2.9.

Online gameplay number flow and calculations should be working as intended now, without having to disconnect and reconnect to make things sync.

Ideally, game numbers will need to feel easier for the upcoming 0.3 Ruleset, but that's a different issue regarding game design, rather than netcode issues.
