### ISSUE TITLE
Online Co-op: Sync ranged weapon rotation aiming and casting

### ISSUE THREAD

**Issue by ChrisNZL** [ChrisNZL/Tallowmere2#773]
Currently in 0.2.2, clients do not sync their ranged weapon rotations/angles when aiming at enemies. It's all cosmetically client-based.

Room for improvement.

---

Additionally, weapons do not necessarily perform their attack sequence across all clients if screen resolution and/or aspect ratio is different between clients.

### TODO:

- [x] Sync rotation aiming better.
- [x] Force sync weapons to attack across all clients, regardless of screen differences.
- [x] Ensure Multishot attacks are synced.
    - `RangedWeapon.ShouldLaunchExtraProjectilesRightNow`
    - ... `creatureStruct.AlterantTracker.coreAttribute_multishotChance.LaunchExtraProjectilesRightNow`
    - ... `AlterantExtension_Bow` ... `weapon.ShouldLaunchExtraProjectilesRightNow`
    - ... `AlterantExtension_Lightning` ... `parentCreatureStruct.AlterantTracker.coreAttribute_multishotChance.LaunchExtraProjectilesRightNow`
    - `Weapon` ... `GuaranteedToLaunchExtraProjectilesThisFrame`, `TotalCreaturesToGetWhenLaunchingExtraProjectiles`
    - `AlterantExtension_Grenade` ... `weapon.ShouldLaunchExtraProjectilesRightNow`
  
- [x] Ensure SeedFactory values are synced for attacks.
    - `NetworkMessage_SetCreatureAttackState` contains the `int seed` for attacks.

- [x] Ensure Storm Cloud attacks are synced

**Comment by ChrisNZL** [comment]
### Fixed and improved in 0.3.5, online co-op:

- Aiming for all clients is now properly synced, even if targets are off-screen on certain clients, especially for Bow and Elemental Staff.

- Multishot attacks are now properly synced.

- Storm Cloud attacks are now properly synced.

---

Internally, added new NetworkMessages:
- `SetCreatureAimTargets`
- `SetNextBoomerangTarget`
- `DoStormCloudAttack`
