### ISSUE TITLE
Online Co-op: Improve server browser

### ISSUE THREAD

**Issue by ChrisNZL** [ChrisNZL/Tallowmere2#840]
Server browser is too squished on mobile as of 0.2.3, and is generally not elegant.

### Tasks – completed in 0.2.4:
- [x] Convert server list from context-menu to regular menu items
- [x] Improve right-panel layout
- [x] Automatically select best-ping server when first refreshing the list – add a small delay before showing the list, giving pings time to update before showing initially

### Future tasks:
- [ ] Add a geographical map
- [ ] Add filter options to sort by ping, name, country
- [ ] Probably show which servers have saved games the player can resume from (though online game-saving may be server-agnostic, able to change servers)

### Related issues:
- [Online Co-op: Add matchmaking #767](https://github.com/ChrisNZL/Tallowmere2/issues/767)
- [Online Co-op: Allow servers to save online games #516](https://github.com/ChrisNZL/Tallowmere2/issues/516)

**Comment by ChrisNZL** [comment]
Improved in 0.2.4:

![image](https://user-images.githubusercontent.com/280814/108608172-30234b80-742a-11eb-9977-19c7ba6eef95.png)
