### ISSUE TITLE
Online Co-op: Room mis-matching continued

### ISSUE THREAD

**Issue by ChrisNZL** [ChrisNZL/Tallowmere2#846]
Auto report. 0.2.3. Online Co-op.

Client Feedback ID: 20210129-DTFTN
Server: HongKong
GameID: PG23H

No errors on server side.

Possibly is a room mis-match timing issue somewhere... 

Comparing server and client logs, incorrect rooms are being requested:
![image](https://user-images.githubusercontent.com/280814/106173164-82d96100-61f8-11eb-8491-79233650ea4d.png)

### Probable causes
I suspect:
- Client A loaded their room, but Client B might have been lagging.
- Then a mob or explosion knocked both players back into a corridor, causing a room transition while one client had not loaded properly.
- Meanwhile then, Client A has loaded one room, but Client B has loaded a different room.

### ⏩ Tasks todo:
- [x] Let server be in control saying which room should be loaded, rather than relying on client to expect a certain particular room number

- [x] Try to prevent new room transitions from occurring until all clients have at least loaded their correct room and have sent an action to say they've loaded in properly. (not sure if this happens at the moment)

- [ ] Detect room mis-matches. If client's room does not match server's room, have the client perform a resync.

Still, if client is not loading the correct room (and room is null), game should probably disconnect and reconnect automatically to get back into sync – or 💡 **perform a full re-sync** (to keep things feeling smooth).

Client log:

```
11:24:43, Frame 144996, ERROR »  ERROR: DungeonRoomTransitioner.Update: UpdatingPlayerCreatureStructs: roomStruct is null. toRoomNumber: 18
>>>>> CRITICAL ERROR >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>


GameStates: InitialisingAsNetworkHost, RompingThroughDungeon, TransitioningToDungeonRoom
OnlineGameInfo: Device is online.
Server: HostUS-HongKong-01
GameID: PG23H
GameSetupMode: NetworkCoop
Players: 2
DungeonRoomTransitionerState: UpdatingPlayerCreatureStructs
Room: 17 / 17
RoomModifiers: LargeRoom (大型房间), HugeProjectiles (巨型抛射物), Hearty (有心有力)
YouHaveDiedState: Null
SystemPlayer InputDevice: 键盘
HumanPlayer 1 InputDevice: 键盘
```

---

Additional feedback ID: 20210202-232PX

**Comment by ChrisNZL** [comment]
Fixed in 0.2.6.

- Server now keeps better track of which players have loaded the current room:
  - List is reset when the room changes.
  - Player is removed from the list if player disconnects.

- Server now has a 2-second wait-period after a player loads, which prevents the server from changing rooms and sending room-change messages until the wait period has finished.

- Added a mini warning message, "Waiting for players to load..." for when the captain is trying to initiate a room transition, but not all players are ready.
