### ISSUE TITLE
Null ref: T2.ScriptedSequence_RescueKittenAndReceiveBlessing.Update

### ISSUE THREAD

**Issue by ChrisNZL** [ChrisNZL/Tallowmere2#849]
Auto report from 3 players at same time during an online co-op game. v0.2.3.

Feedback IDs: 20210130-VT4N2, 20210130-7DXC8, 20210130-MNS4K

Server: Lightning-Beijing-01
GameID: 6JZB5

Server game log has a warning regarding `GrantBlessing`, and the players disconnected about a minute later on their own accord.

I assume this is a timing/sync issue regarding a kitten dying and a blessing trying to be granted... Cutscene failing to find a kitten I imagine.

### Tasks todo:
- [ ] See if damage and cutscene packets can be synced better. This was supposedly fixed in 0.2.3 where damage messages no longer process if a cutscene was started. However, perhaps a cutscene was initiated _after_ a kitten died.

- [x] Make cutscene-initiation more robust – check the kitten involved is alive before sending message to initiate the cutscene.

- [x] For both server and clients, ensure clients are not going to stall.

```
11:36:22, Frame 41830292, LOG »  transitionState: Inactive
fromRoomNumber: 4
toRoomNumber: 5
fromObjectNetID: Master452
dict_playerStatuses.Count: 3
timer_transitionStarted.HasDuration: False
timer_transitionStarted.IsDone: False

All players are ready to reveal the room.
Telling clients to reveal...

11:37:21, Frame 41833864, WARNING »  WARNING: GrantBlessing:
kittenCreatureStruct not found with netID Master504

11:37:42, Frame 41835069, LOG »  RelayServer._OnPeerDisconnected: gameStruct Master250: Removing NetPeer for playerStructNetID Master63

11:37:42, Frame 41835069, LOG »  PLAYER DISCONNECTED.
playerStructNetID: Master63
playerDisconnectionType: Soft

11:38:04, Frame 41836409, LOG »  RelayServer._OnPeerDisconnected: gameStruct Master250: Removing NetPeer for playerStructNetID Master1

11:38:04, Frame 41836409, LOG »  PLAYER DISCONNECTED.
playerStructNetID: Master1
playerDisconnectionType: Soft

11:38:06, Frame 41836525, LOG »  RelayServer._OnPeerDisconnected: gameStruct Master250: Removing NetPeer for playerStructNetID Master58

11:38:06, Frame 41836525, LOG »  PLAYER DISCONNECTED.
playerStructNetID: Master58
playerDisconnectionType: Soft
```

**Comment by ChrisNZL** [comment]
Another report, from two players

Feedback IDs:
- 20210205-C3536
- 20210205-55WVF

Server: Lightning-Beijing-01
GameID: 8SHN5

```
8:31:17, Frame 324459, EXCEPTION »  NullReferenceException: Object reference not set to an instance of an object
>>>>> CRITICAL ERROR >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

T2.ScriptedSequence_RescueKittenAndReceiveBlessing.Update ()

GameStates: RompingThroughDungeon, ShowingCutscene, PromptingToSkipCutscene
OnlineGameInfo: Device is online.
Server: Lightning-Beijing-01
GameID: 8SHN5
GameSetupMode: NetworkCoop
Players: 3
DungeonRoomTransitionerState: Null
Room: 30 / 30
RoomModifiers: None
YouHaveDiedState: Null
SystemPlayer InputDevice: 键盘
HumanPlayer 1 InputDevice: 键盘
```

**Comment by ChrisNZL** [comment]
Fixed in 0.2.5.

**Comment by ChrisNZL** [comment]
Further null error. 0.2.6a.

- Feedback IDs: 20210403-X3LK8, 20210403-LDXSR
- Server: Lightning-Beijing-01
- GameID: CH4YD

No errors server-side.

### Need to:
- Break down the `Update` method into smaller methods.
- Add more null checks.

**Comment by ChrisNZL** [comment]
Auto report from v0.3.0.

Feedback ID: 20211224-BC9PN

```
8:28:45, Frame 338822, LOG »  NetworkMessage_DungeonRoomTransitionHelper: Received message.
Desire: 4 » BeginLoadingRoom


8:28:45, Frame 338847, LOG »  NetworkMessage_DungeonRoomTransitionHelper: Received message.
Desire: 6 » RevealRoom

8:28:45, Frame 338848, LOG »  DungeonRoomTransitioner.Update: Revealing room: 第15个房间：烈火洞窟


8:30:38, Frame 345612, EXCEPTION »  NullReferenceException: Object reference not set to an instance of an object
>>>>> CRITICAL ERROR >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

T2.ScriptedSequence_RescueKittenAndReceiveBlessing.Update ()

GameStates: RompingThroughDungeon, ShowingCutscene
OnlineGameInfo: Device is online.
Server: Lightning-Beijing-01
GameID: 8VT3Z
GameSetupMode: NetworkCoop
Players: 2
DungeonRoomTransitionerState: Null
Room: 15 / 15
RoomModifiers: None
YouHaveDiedState: Null
SystemPlayer InputDevice: 键盘
HumanPlayer 1 InputDevice: 键盘
```

**Comment by ChrisNZL** [comment]
Hoping this is fixed in 0.3.1. Added more null checks.

**Comment by ChrisNZL** [comment]
Version 0.3.3, auto reports, online game, three players, null refs

Feedback IDs: `20220221-JXXN8`, `20220221-CZZX8`, `20220221-3BDMY`

Looks like kitten became slain shortly/immediately after rescuing cutscene started.

### TO INVESTIGATE:
 Double-check server-side methods:
- [ ] Ensure scripted sequence can't start if kitten has been slain.
- [ ] Ensure kitten can't be slain if related sequence has been started.

```
1:37:30, Frame 284161, LOG »  Player Gocy has fallen!
1:38:19, Frame 287095, LOG »  Player Gocy has been revived.
1:38:21, Frame 287186, LOG »  NetworkMessage_MakeCreatureDrinkPotion: simpleItemStruct.Quantity is now 1
1:38:39, Frame 288302, LOG »  ScriptedSequenceStarter.OnCreaturePressedActionToInteract: Telling server to start sequence.

1:38:39, Frame 288307, LOG »  Cutscene.ShowBlackBars: Telling server to start cutscene.
requiredKittenNetID is Master0


1:38:39, Frame 288308, LOG »  Creature.SlayOrFallOver: A kitten has been slain!
Kitten's MaxHealth was 8.
GameStates: GameStates: InitialisingAsNetworkHost, RompingThroughDungeon, ShowingCutscene



1:38:45, Frame 288654, EXCEPTION »  NullReferenceException: Object reference not set to an instance of an object
>>>>> CRITICAL ERROR >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

T2.ScriptedSequence_RescueKittenAndReceiveBlessing.Update ()

GameStates: InitialisingAsNetworkHost, RompingThroughDungeon, ShowingCutscene, PromptingToSkipCutscene, ViewingAlertBox
AlertBox.currentAlert:
- alert.id: PromptToSkipCutscene
- alert.title: 
- alert.description: 投票决定是否跳过过场动画？
OnlineGameInfo: Device is online.
Server: Lightning-Beijing-01
GameID: YZ52F
GameSetupMode: NetworkCoop
Players: 3
DungeonRoomTransitioner.state: Null
DungeonRoom.state: Ready
Room: 20 / 20
RoomModifiers: None
YouHaveDiedState: Null
SystemPlayer InputDevice: 键盘
HumanPlayer 1 InputDevice: 键盘
```

**Comment by ChrisNZL** [comment]
Additional feedback ID: `0.3.7p_20230221-FXNQZ`

**Comment by ChrisNZL** [comment]
Haven't had errors of this in a long time.
