### ISSUE TITLE
Feedback System: Add progress bar; handle timeouts better

### ISSUE THREAD

**Issue by ChrisNZL** [ChrisNZL/Tallowmere2#871]
When using the feedback form, there are issues of web requests timing out (`7` seconds as of 0.2.4).

### Todo:
- [x] Increase timeout
- [ ] Display amount of data in KB to be transferred
- [x] Add a progress bar
- [ ] Double-check how timeout issues are handled

**Comment by ChrisNZL** [comment]
Timeout was increased to `10` seconds in version 0.3.4.

AlertBox now shows an infinite progress bar in 0.3.5 (in tandem with issue #1023).

Might revisit the byte/data size count later.
