### ISSUE TITLE
ERROR: PlayerStruct constructor (NetDataReader)

### ISSUE THREAD

**Issue by ChrisNZL** [ChrisNZL/Tallowmere2#894]
Auto report. 0.2.6a. Feedback IDs: 20210413-LK3NM, 20210413-5XMFN, 20210413-PNGCW

All three reports show the device as being Disconnected with the Alert Box, so it sounds like the client has disconnected.

Device should just reset back to title screen if error happens during the PlayerStruct constructor in this instance, since game is trying to create a new NetIDDatabase for a new game, but it's failing due to errors during restart and disconnection.

### Tasks todo:

- [x] Make Alert Box log its contents when an error occurs.
- [ ] Make game restart back to title screen automatically during PlayerStruct constructor failing with these game states: `Disconnected, RompingThroughDungeon, ViewingHighScoreCanvas, ViewingAlertBox`

```
10:46:12, Frame 41626, ERROR »  ERROR: PlayerStruct constructor (NetDataReader):
No case for headerByte 230
debug_calledFrom: NetIDDatabase constructor
hasReadPreviousHeaderByte: True
previousHeaderByte: 2
>>>>> CRITICAL ERROR >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>


GameStates: Disconnected, RompingThroughDungeon, ViewingHighScoreCanvas, ViewingAlertBox
OnlineGameInfo: Device is offline.
Previous server: Lightning-Beijing-01
Previous GameID: LH8CC
GameSetupMode: NetworkCoop
Players: 2
DungeonRoomTransitionerState: Null
Room: 6 / 6
RoomModifiers: MediumRoom (中型房间)
YouHaveDiedState: Visible
SystemPlayer InputDevice: 键盘
HumanPlayer 1 InputDevice: 键盘
```

Related issue: [Online Co-op: ERROR: No case for PlayerStruct HeaderByte 230 #848](https://github.com/ChrisNZL/Tallowmere2/issues/848)

**Comment by ChrisNZL** [comment]
Fresh reports. 0.2.8a. Feedback IDs: 20210918-LTGQM, 20210918-84FXB

### First, a manually-submitted report with a message, and the log:

>I can't find my friend's server online. My friend can find my server, but can't get in?

```
11:56:08, Frame 610, LOG »  Account.t2 file found. byte length: 1,024. Importing...
11:56:08, Frame 610, LOG »  STEAM: Requesting stats and achievements from Steam...
11:56:08, Frame 610, LOG »  InputLibraryProfile: Activating InControl
11:56:13, Frame 847, WARNING »  WARNING: Category OnlineCoop_Join is empty. 1631894173
[[[ ^ REPEATING MESSAGE... ]]]

11:56:13, Frame 875, LOG »  STEAM: Received stats and achievements from Steam.
11:56:13, Frame 875, LOG »  STEAM: Total achievements earned: 1
11:56:20, Frame 1193, WARNING »  WARNING: Category OnlineCoop_Join is empty. 1631894180
11:56:26, Frame 1280, WARNING »  WARNING: Category OnlineCoop_Join is empty. 1631894186
11:57:24, Frame 1595, WARNING »  WARNING: Category OnlineCoop_Host is empty. 1631894244
[[[ ^ REPEATING MESSAGE... ]]]


11:57:29, Frame 1919, LOG »  RELAY CLIENT: Connecting to server.
Intention: ConnectingAsHost

11:57:30, Frame 1964, LOG »  NETWORK CLIENT: Connecting to 123.56.71.67:5889 ...
11:57:30, Frame 1967, LOG »  Device.OnBecameOnline: Device is now online.
11:57:30, Frame 1967, LOG »  NETWORK CLIENT: RelayClient connected to server 123.56.71.67:5889

11:57:30, Frame 1967, LOG »  Sending handshakeStruct to server: NetworkHandshakeStruct:
clientIntention.id: ConnectingAsHost
newPlayerJoiningAccountDisplayName: XXXXX
lastUsedPlayerInfo.couchCoopPlayerName: XXXXX


11:57:30, Frame 1970, LOG »  NETWORK HANDSHAKE: Connected.
Device is online.
Server: Lightning-Beijing-01
GameID: JGJNT


11:57:31, Frame 2018, LOG »  NetworkMessage_DungeonRoomTransitionHelper: Received message.
Desire: 4 » BeginLoadingRoom

11:57:32, Frame 2040, LOG »  DungeonRoomTransitioner.Update: Revealing room: Tallowmere的城堡
11:57:50, Frame 3106, WARNING »  WARNING: playerStruct not found for netID Master58
11:58:45, Frame 6350, WARNING »  WARNING: playerStruct not found for netID Master63
11:58:53, Frame 6822, WARNING »  WARNING: playerStruct not found for netID Master68
```

---

### Second, a couple hours later, client has disconnected due to a timeout, then looks like they attempted to reconnect via Online Co-op > "Load Game" rather than "Join Game"

```
1:32:52, Frame 342844, LOG »  DungeonRoomTransitioner.Update: Revealing room: 第27个房间：圣堂

1:33:03, Frame 343493, LOG »  NetworkMessage_DungeonRoomTransitionHelper: Received message.
Desire: 1 » EnterCorridor


1:33:03, Frame 343493, LOG »  NetworkMessage_DungeonRoomTransitionHelper:
Desire_EnterCorridor: Entering corridor...

1:33:03, Frame 343493, LOG »  DungeonRoomTransitioner.BeginTransitioningToRoom: Departing room 27...

1:33:04, Frame 343542, LOG »  NetworkMessage_DungeonRoomTransitionHelper: Received message.
Desire: 4 » BeginLoadingRoom


1:33:05, Frame 343567, LOG »  NetworkMessage_DungeonRoomTransitionHelper: Received message.
Desire: 6 » RevealRoom

1:33:05, Frame 343568, LOG »  DungeonRoomTransitioner.Update: Revealing room: 第28个房间：圣堂
1:33:10, Frame 343914, WARNING »  NETWORK CLIENT: RelayClient disconnected: Timeout
1:33:10, Frame 343914, LOG »  Device.OnBecameOffline: Device is now offline.
1:33:15, Frame 344179, LOG »  Returning to title screen...

1:33:25, Frame 344788, LOG »  RELAY CLIENT: Connecting to server.
Intention: GettingOnlineCoopSavedGames

1:33:25, Frame 344789, WARNING »  WARNING: Category Play_Load is empty. 1631900005
1:33:26, Frame 344833, LOG »  NETWORK CLIENT: Connecting to 123.56.71.67:5889 ...
1:33:26, Frame 344837, LOG »  Device.OnBecameOnline: Device is now online.
1:33:26, Frame 344837, LOG »  NETWORK CLIENT: RelayClient connected to server 123.56.71.67:5889

1:33:26, Frame 344837, LOG »  Sending handshakeStruct to server: NetworkHandshakeStruct:
clientIntention.id: GettingOnlineCoopSavedGames
newPlayerJoiningAccountDisplayName: XXXXX
lastUsedPlayerInfo.couchCoopPlayerName: XXXXX

1:33:26, Frame 344842, LOG »  NetworkMessage_GetOnlineCoopSavedGames: Received message. byteStruct.bytes.Length: 16384
1:33:26, Frame 344842, LOG »  Total byte arrays on game state: 1
1:33:26, Frame 344849, LOG »  NetworkMessage_GetOnlineCoopSavedGames: Received message. byteStruct.bytes.Length: 131072
1:33:26, Frame 344849, LOG »  Total byte arrays on game state: 2
1:33:26, Frame 344849, LOG »  HANDSHAKE: Finished downloading online co-op saved games. Disconnecting now.
1:33:26, Frame 344849, LOG »  Device.OnBecameOffline: Device is now offline.


1:33:26, Frame 344849, ERROR »  ERROR: PlayerStruct constructor (NetDataReader):
No case for headerByte 228
debug_calledFrom: NetIDDatabase constructor
hasReadPreviousHeaderByte: True
previousHeaderByte: 2
>>>>> CRITICAL ERROR >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>


GameStates: ShowingTitleScreen, UsingMainMenu
OnlineGameInfo: Device is offline.
Previous server: Lightning-Beijing-01
Previous GameID: 53FMD
SystemPlayer InputDevice: 键盘
```

---

So, it sounds like the player figured out how to use the menus for "Join Game" and "Load Game" when playing online.

Some errors / flow to investigate with attempting to reconnect via "Load Game" however.

Related issue is to improve the "play with friends" flow however: [Online Co-op: Improve flow when trying to load/resume online co-op game #897](https://github.com/ChrisNZL/Tallowmere2/issues/897)

**Comment by ChrisNZL** [comment]
Another auto report, v0.2.8a, Feedback ID: 20210922-5JK33

```
7:28:57, Frame 97417, WARNING »  NETWORK CLIENT: RelayClient disconnected: RemoteConnectionClose
7:28:57, Frame 97417, LOG »  Device.OnBecameOffline: Device is now offline.
7:28:57, Frame 97466, LOG »  Returning to title screen...

7:29:16, Frame 98599, LOG »  RELAY CLIENT: Connecting to server.
Intention: GettingOnlineCoopSavedGames

7:29:16, Frame 98600, WARNING »  WARNING: Category Play_Load is empty. 1632310156
7:29:17, Frame 98644, LOG »  NETWORK CLIENT: Connecting to 123.56.71.67:5889 ...
7:29:17, Frame 98650, LOG »  Device.OnBecameOnline: Device is now online.
7:29:17, Frame 98650, LOG »  NETWORK CLIENT: RelayClient connected to server 123.56.71.67:5889

7:29:17, Frame 98650, LOG »  Sending handshakeStruct to server: NetworkHandshakeStruct:
clientIntention.id: GettingOnlineCoopSavedGames
newPlayerJoiningAccountDisplayName: 你这个笨蛋闲着看我ID干什么
lastUsedPlayerInfo.couchCoopPlayerName: 1号玩家

7:29:17, Frame 98658, LOG »  NetworkMessage_GetOnlineCoopSavedGames: Received message. byteStruct.bytes.Length: 16384
7:29:17, Frame 98658, LOG »  Total byte arrays on game state: 1
7:29:18, Frame 98670, LOG »  NetworkMessage_GetOnlineCoopSavedGames: Received message. byteStruct.bytes.Length: 131072
7:29:18, Frame 98670, LOG »  Total byte arrays on game state: 2
7:29:18, Frame 98670, LOG »  NetworkMessage_GetOnlineCoopSavedGames: Received message. byteStruct.bytes.Length: 16384
7:29:18, Frame 98670, LOG »  Total byte arrays on game state: 3
7:29:18, Frame 98674, LOG »  NetworkMessage_GetOnlineCoopSavedGames: Received message. byteStruct.bytes.Length: 32768
7:29:18, Frame 98674, LOG »  Total byte arrays on game state: 4
7:29:18, Frame 98674, LOG »  HANDSHAKE: Finished downloading online co-op saved games. Disconnecting now.
7:29:18, Frame 98674, LOG »  Device.OnBecameOffline: Device is now offline.


7:29:18, Frame 98674, ERROR »  ERROR: PlayerStruct constructor (NetDataReader):
No case for headerByte 228
debug_calledFrom: NetIDDatabase constructor
hasReadPreviousHeaderByte: True
previousHeaderByte: 2
>>>>> CRITICAL ERROR >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>


GameStates: ShowingTitleScreen, UsingMainMenu
OnlineGameInfo: Device is offline.
No previous server nor online game info.
SystemPlayer InputDevice: 键盘
```

**Comment by ChrisNZL** [comment]
## TODO:
- [ ] Test saving an online co-op game with a player name longer than 16 characters
- [ ] Test saving an online co-op game with a player name longer that has no length, or is null

## Investigation notes:
PlayerStruct.cs >>
```csharp
const byte HeaderByte_Name = 2;
```
^ this is likely the `previousHeaderByte: 2` that the constructor reads.

PlayerStruct constructor calls:
```csharp
case HeaderByte_Name:
	name = reader.GetString(PlayerStruct.MaxNameLength);
	break;
```

When adding PlayerStruct to NetDataWriter via `AddBytesToWriter`, code goes:
```csharp
// name
if (Has.Length(name)) {
	int maxLength = PlayerStruct.MaxNameLength;
	string nameForWriter = name.Length > maxLength ? name.Substring(0, 16) : name;
	writer.Put(HeaderByte_Name);
	writer.Put(nameForWriter, maxLength);
}
```

^ above, `16` should probably use `maxLength`.

**Comment by ChrisNZL** [comment]
Should be fixed in 0.3.1.

Identified issues with LiteNetLib's `NetDataWriter.Put(string value, int maxLength)` and `NetDataReader.GetString(int maxLength)` methods.

Made some fixes/changes locally, and have submitted a [pull request to LiteNetLib](https://github.com/RevenantX/LiteNetLib/pull/467).

_Tallowmere 2_, for now, uses code:
- from LiteNetLib's master indev 1.0 branch for `NetDataWriter.Put(string value, int maxLength)` (the 0.9 branch's method is buggy), and
- my proposed change for `NetDataReader.GetString(int maxLength)`.

My proposed change, while submitted to LiteNetLib's indev 1.0 branch, is backwards-compatible with strings written to disk via LiteNetLib 0.9.
