### ISSUE TITLE
Steam + macOS: Update to latest Steamworks.NET

### ISSUE THREAD

**Issue by ChrisNZL** [ChrisNZL/Tallowmere2#922]
With 0.2.8 using Unity 2020.3, there's some issues with the older version of Steamworks.NET not working with macOS, resulting in a hard crash upon startup:

```
7:48:52, Frame 583, LOG »  Tallowmere 2 v0.2.8 (Steam)
7:48:52, Frame 583, LOG »  /Users/chris/Library/Application Support/Steam/steamapps/common/Tallowmere 2/Tallowmere 2.app/Contents/MacOS/Tallowmere 2
7:48:52, Frame 583, LOG »  Local Date: Monday, 9 August 2021 @ 7:48 p.m.
7:48:52, Frame 583, LOG »  OS: MacOSX, Mac OS X 11.5.1
7:48:52, Frame 583, LOG »  CPU: Intel(R) Core(TM) i3-8100B CPU @ 3.60GHz, 3,600 MHz, 4 cores
7:48:52, Frame 583, LOG »  RAM: 8,192 MB
7:48:52, Frame 583, LOG »  GPU: Intel(R) UHD Graphics 630, 1,536 MB
7:48:52, Frame 583, LOG »  Device Name + Model: Mac mini, Macmini8,1
7:48:53, Frame 583, LOG »  STEAM: Hooking into Steam...


7:48:53, Frame 583, EXCEPTION »  DllNotFoundException: steam_api
>>>>> CRITICAL ERROR >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

Steamworks.SteamAPI.Init ()
T2.Platform_Steam.StartStartingForStartup ()
T2.Startup.LateUpdate ()

OnlineGameInfo: Device is offline.
No previous server nor online game info.
```

Need to update to latest version of Steamworks.NET, and update Steamworks SDK too.

macOS issues I am encountering on older Steamworks.NET version:
- https://github.com/rlabrecque/Steamworks.NET/issues/401
- https://github.com/rlabrecque/Steamworks.NET/issues/393

The Steamworks.NET commit that should fix the above:
- https://github.com/rlabrecque/Steamworks.NET/pull/414

### Desired version – 15.0.1:
- https://github.com/rlabrecque/Steamworks.NET/releases/tag/15.0.1

> Feature: Update to **Steamworks SDK 1.51**
> Feature: New Callback Mechanism with support for **IL2CPP**

### Tasks:

- [x] Implement Steamworks.NET 15.0.1 into Unity project.
- [x] Locally, update to a `steamworks_sdk_151` folder (or similar) and grab the Steamworks SDK 1.51 from Valve.
- [ ] _Optional:_ See if IL2CPP builds are viable for desktop. Previously, IL2CPP desktop builds would fail due to Steamworks.NET requiring Mono.

**Comment by ChrisNZL** [comment]
Implemented successfully into version 0.2.8.

For Inspector options for various `steam_api` files, I've selected `Any CPU` for both macOS and Linux targets; seems okay.

Worth noting for macOS builds, a warning is spouted, but the build remains okay and runs succesfully when delivered through Steam:

> Deleting 'C:\UnityProjects\Tallowmere2_Jan2017\Temp\StagingArea\Tallowmere 2.app\Contents\PlugIns\libsteam_api.so' because it cannot be signed.

**Comment by ChrisNZL** [comment]
IL2CPP testing will be an experiment for another day. Requires Visual Studio. Will stick with Mono for now.
