### ISSUE TITLE
Room 900+: NetIDDatabase has run out of ushorts to allocate

### ISSUE THREAD

**Issue by ChrisNZL** [ChrisNZL/Tallowmere2#957]
Auto report. Version 0.2.8a. Feedback ID with savedgame: 20210908-GPXGP

A player has reached Room 933 with over 20 hours of play time.

![image](https://user-images.githubusercontent.com/280814/133339174-f524d9b5-d446-4d30-af31-df3689fb5b8b.png)

![image](https://user-images.githubusercontent.com/280814/133339548-390e3962-9689-4365-8eeb-67ee4d793075.png)

However, the savefile's internal `NetIDDatabase` has run out of ushorts to allocate, to the point that some enemies can't even instantiate their own weapons.

At a glance, items in the Merchant Buyback tab are never vacuumed. Perhaps they should be vacuumed after a few rooms.

![image](https://user-images.githubusercontent.com/280814/133339919-61c93581-9643-4980-95ff-2158cf7c748d.png)

### TODO / To investigate:
- [x] Are enemy weapons being removed from `gameStruct.netIDDatabase` when a creature dies?
  - Yes, weapons from enemies get removed correctly. However, enemies did not get vacuumed.
- [x] Inspect / debug how many weapons, items, creatures, etc, are taking up the savefile's data and structure.
  - Chests were not being vacuumed, nor their items, nor enemies that were alive and their items. Merchant Buyback items were forever remaining too.
- [x] Double-check what is getting vacuumed / improve the `NetIDDatabase.Vacuum` method if possible.
- [x] Attempt to improve vacuuming the savefile upon load.
- [ ] If it's still a problem, perhaps show an alert about the savefile being at max capacity, or load it and handle it somehow.
- [ ] Maybe add a room number cap 😜
- [x] Add a limit to the number of items the Merchant can hold in their Buyback tab.
  - Buyback item limit is now 25 rather than unlimited. Applied when the game gets saved.

---

## Logs

Previous log shows game started having errors after entering a room:

```
2:09:11, Frame 61512, LOG »  DungeonRoomTransitioner.BeginTransitioningToRoom: Departing room 925...
2:09:18, Frame 61876, LOG »  DungeonRoomTransitioner.Update: Revealing room: 第926个房间：牢房
2:10:08, Frame 64900, LOG »  DungeonRoomTransitioner.BeginTransitioningToRoom: Departing room 926...
2:10:10, Frame 64971, LOG »  DungeonRoomTransitioner.Update: Revealing room: 第927个房间：牢房
2:10:28, Frame 66016, LOG »  DungeonRoomTransitioner.BeginTransitioningToRoom: Departing room 927...
2:10:30, Frame 66087, LOG »  DungeonRoomTransitioner.Update: Revealing room: 第928个房间：牢房
2:11:01, Frame 67950, LOG »  DungeonRoomTransitioner.BeginTransitioningToRoom: Departing room 928...
2:11:06, Frame 67986, LOG »  DungeonRoomTransitioner.Update: Revealing room: 第929个房间：牢房
2:11:25, Frame 69135, LOG »  DungeonRoomTransitioner.BeginTransitioningToRoom: Departing room 929...
2:11:28, Frame 69206, LOG »  DungeonRoomTransitioner.Update: Revealing room: 第930个房间：牢房
2:12:08, Frame 71651, LOG »  DungeonRoomTransitioner.BeginTransitioningToRoom: Departing room 930...
2:12:16, Frame 72015, LOG »  DungeonRoomTransitioner.Update: Revealing room: 第931个房间：烈火洞窟
2:12:41, Frame 73565, LOG »  DungeonRoomTransitioner.BeginTransitioningToRoom: Departing room 931...
2:12:44, Frame 73636, LOG »  DungeonRoomTransitioner.Update: Revealing room: 第932个房间：烈火洞窟
2:13:09, Frame 75042, LOG »  DungeonRoomTransitioner.BeginTransitioningToRoom: Departing room 932...

2:13:11, Frame 75094, ERROR »  ERROR: NetIDDatabase has run out of ushortValues for netIDType Master
>>>>> CRITICAL ERROR >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

GameStates: RompingThroughDungeon, TransitioningToDungeonRoom
OnlineGameInfo: Device is offline.
No previous server nor online game info.
GameSetupMode: Singleplayer
Players: 1
DungeonRoomTransitionerState: CreatingNewRoomStructIfNeeded
Room: 932 / 933
RoomModifiers: Hearty (有心有力), Penniless (家徒四壁), BowsOnly (弓箭练习), LargeRoom (大型房间), Spiky (满屋尖刺)
YouHaveDiedState: Null
SystemPlayer InputDevice: 键盘
HumanPlayer 1 InputDevice: 键盘
```

Then, after closing the application and opening the application, game throwing errors when reading the saved game (yet the savefile still loads):

```
2:14:38, Frame 573, LOG »  FILESYSTEM: Steam Cloud is enabled.
2:14:38, Frame 573, LOG »  FILESYSTEM: Begin loading files using AsyncFileManager_Steam...
2:14:38, Frame 573, LOG »  STEAM CLOUD: Requesting to read file: SavedGame.001.t2 ...
2:14:38, Frame 573, LOG »  FILESYSTEM: Total files queued to be read: 5
2:14:38, Frame 574, LOG »  STEAM CLOUD: Finished reading file: SavedGame.001.t2. bytes: 2,918,008
2:14:38, Frame 574, LOG »  STEAM CLOUD: Requesting to read file: SavedGame.002.t2 ...
2:14:38, Frame 575, LOG »  STEAM CLOUD: Finished reading file: SavedGame.002.t2. bytes: 3,214
2:14:38, Frame 575, LOG »  STEAM CLOUD: Requesting to read file: SavedGame.003.t2 ...
2:14:38, Frame 576, LOG »  STEAM CLOUD: Finished reading file: SavedGame.003.t2. bytes: 184,165
2:14:38, Frame 576, LOG »  STEAM CLOUD: Requesting to read file: Options.Synced.ini ...
2:14:38, Frame 577, LOG »  STEAM CLOUD: Finished reading file: Options.Synced.ini. bytes: 759
2:14:38, Frame 577, LOG »  STEAM CLOUD: Requesting to read file: Account.t2 ...
2:14:38, Frame 578, LOG »  STEAM CLOUD: Finished reading file: Account.t2. bytes: 2,048
2:14:38, Frame 578, LOG »  AsyncFileManager_Steam: Total files loaded: 10
2:14:38, Frame 578, LOG »  Signed in (if supported). Loading options...
2:14:38, Frame 578, LOG »  Account.t2 file found. byte length: 2,048. Importing...
2:14:38, Frame 578, LOG »  STEAM: Requesting stats and achievements from Steam...
2:14:38, Frame 578, LOG »  InputLibraryProfile: Activating InControl
2:14:39, Frame 584, LOG »  STEAM: Received stats and achievements from Steam.
2:14:39, Frame 584, LOG »  STEAM: Total achievements earned: 56

2:14:42, Frame 737, ERROR »  ERROR: Can't add networked Class WeaponStruct to netIDDatabase. tallowClass.netID.ushortValue == 0
>>>>> CRITICAL ERROR >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

GameStates: ShowingTitleScreen, UsingMainMenu
OnlineGameInfo: Device is offline.
No previous server nor online game info.
SystemPlayer InputDevice: 键盘
```

**Comment by ChrisNZL** [comment]
Fixed in 0.2.9.

### Issue: 
- As you progress in the dungeon, rooms from 5-10 rooms ago quietly get vacuumed; eg mostly destroyed in the savefile, and the doors to access the old rooms get closed since the old rooms aren't accessible. Home room's eastern door also becomes closed after 5-10 rooms or so.

- Issue identified where old rooms did not have their DungeonRoomObjects removed when the `NetIDDatabase.Vacuum` method would execute, meaning chests, items in chests, pedestals, traps, waypoints, etc, would forever be retained in the savefile, taking up space hogging much-needed NetID ushort allocation.

- Enemies that were not slain, and their weapons, would also be retained.

- Items sold to the Merchant would also be retained in the Buyback tab.

### Fixed now:

- Old enemies, chests, items, traps, etc, get vacuumed properly when the game is saved.

- Vacuuming also happens when a savefile is loaded if issues are detected. Some fixes are applied if the game detects the savefile suffered issues in 0.2.8a.

- Merchant now has a limit of 25 Buyback items; pruning is applied when the game is saved.

### Result:

For the savefile in question (Room 933 with 20 hours playtime) that these fixes were tested with:

- Original savefile was 2.8 MB with all 65,535 NetID ushorts allocated and exhausted.

- After the fixes and proper vacuuming, savefile is now 450 KB with just under 3,000 NetID ushorts allocated. About an 84% size reduction in total.
