### ISSUE TITLE
EnemyLevelUpResult: Need to record room number

### ISSUE THREAD

**Issue by ChrisNZL** [ChrisNZL/Tallowmere2#959]
Small issue identified with savefile structure and how enemy/trap numbers are calculated.

The `EnemyLevelUpResult` class does not hold which room number the result was generated in.

So, when you backtrack to a previous room after the "Dungeon grows stronger" intermission is displayed, enemies and traps may feel slightly stronger than before, which is not intended.

### TODO:
- [ ] Adjust `EnemyLevelUpResult` to hold which room number the result was generated in, OR
- [ ] Make each result be stored in a `RoomStruct`, OR
- [ ] Create an `EnemyLevelUpResultSet` that holds a room number and each result.

**Comment by ChrisNZL** [comment]
Added in v0.3 for Ruleset 0.3, for use with enemy/trap health and damage number calculations.

`struct EnemyLevelUpResult` now contains `ushort roomNumber`.
