### ISSUE TITLE
Online Co-op: ERROR: spawnPoint is null!

### ISSUE THREAD

**Issue by ChrisNZL** [ChrisNZL/Tallowmere2#963]
Auto reports. Version 0.2.9.

Feedback IDs:
- 20210929-66NJP
- 20210929-38WDX
- 20210929-39HG2

```
7:12:33, Frame 885916, ERROR »  ERROR: spawnPoint is null!
>>>>> CRITICAL ERROR >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>


GameStates: ShowingTitleScreen, TransitioningToDungeonRoom
OnlineGameInfo: Device is online.
Server: Lightning-Beijing-01
GameID: M8J7Z
SystemPlayer InputDevice: XInput Controller
HumanPlayer 1 InputDevice: XInput Controller
```

**Comment by ChrisNZL** [comment]
Should be fixed in 0.3.0.

See [issue #964 Null ref: T2.DungeonRoomStruct.GetAppropriatePlayerSpawnPointNetID](https://github.com/ChrisNZL/Tallowmere2/issues/964).

**Comment by ChrisNZL** [comment]
Still happening in 0.2.10a.

Feedback IDs:
- 20211115-LHQDN
- 20211115-G5M58
- 20211115-N4QZG
- 20211115-XKPNG

Bug identified... Players have used a waypoint (Room 24 in this case), warped to the home room, but server is receiving a message somewhere to enter a corridor to go from Room 0 to Room 1, wherein Room 1 is supposed to be locked and emptied, hence bug happens.

### TODO:
- [ ] Prevent corridor messages from happening if adjacent room has been emptied... this might be a home room-specific issue, with weird timing of messages.
- [ ] Possibly set specific from/to room numbers - client-side? server-side? might already be in place though, need to check.
- [ ] Prevent transition messages from happening if a destination room has been emptied.


Server log on Vultr-Paris-01, GameID `62P5D`:
```
2:26:02, Frame 60185387, LOG »  transitionState: Inactive
fromRoomNumber: 24
toRoomNumber: 0
fromObjectNetID: Master1862
dict_playerStatuses.Count: 2
timer_transitionStarted.HasDuration: False
timer_transitionStarted.IsDone: False

All players are ready to reveal the room.
Telling clients to reveal...

2:26:08, Frame 60185742, LOG »  SellItemToMerchant: Player Master1 sold item Master1865 to merchant Master24
2:26:11, Frame 60185951, LOG »  SellItemToMerchant: Player Master1 sold item Master1873 to merchant Master24
2:26:18, Frame 60186362, LOG »  SellItemToMerchant: Player Master1 sold item Master1869 to merchant Master24

2:26:53, Frame 60188478, LOG »  NetworkMessage_DungeonRoomTransitionHelper: Received message.
From player: Player: Seven (NetID: Master1)
Desire: 1 » EnterCorridor


2:26:53, Frame 60188478, LOG »  NetworkMessage_DungeonRoomTransitionHelper:
Desire_EnterCorridor: Party is entering corridor...
fromRoomNumber: 0


2:26:53, Frame 60188478, LOG »  gameStruct.dungeonRoomTransitionStatus: transitionState: PlayersAreFadingToBlack
fromRoomNumber: 0
toRoomNumber: 1
fromObjectNetID: Master9
dict_playerStatuses.Count: 2
timer_transitionStarted.HasDuration: True
timer_transitionStarted.IsDone: False
```

**Comment by ChrisNZL** [comment]
Fixed in 0.2.11. Server was Vacuuming emptying rooms, but not sending messages to clients about closed doors. 

Main bug was that a party could waypoint to home room, but east door was never closed after being Vacuumed, so party would enter corridor and become stuck in Room 1.
