### ISSUE TITLE
AI / Traps / Damage / Kittens: Ensure enemies & traps do not deal _anything_ during room loading

### ISSUE THREAD

**Issue by ChrisNZL** [ChrisNZL/Tallowmere2#971]
Also, try to ensure kittens can't be slain if their door is closed.

Report from v0.2.9:

![image](https://user-images.githubusercontent.com/280814/138843682-904995c0-d844-4c67-8cfd-17c184e56e8f.png)

Single-player.

Without a combat log yet (issue #643), hard to detail how/why the kitten died, but I suspect the Leapers swung their weapon and killed the kitten.

But possibly was also due to a pinwheel trap or spinning elemental trap, dealing damage, as those traps leave blood stains when hitting a creature.

### TODO: 
- [ ] Ensure kittens can't be slain if their door is closed.
- [ ] Lock down `CreatureAI.Update`, `CreatureAI.LateUpdate`, `Trap.Update`, `PinwheelTrap.Update`, `Trap_ElementalSpinner.OnUpdate`, `Trap_ElementalSpinner.OnInstantiated`, `TrapBalland other trap methods to ensure damage is not dealt during room loading.
- [ ] Test loading rooms at low framerates, both visually and physics-wise, in case things are instantiating atop each other before moving into position correctly; see if traps (and _maybe_ enemies) are dealing damage when they shouldn't with their colliders due to low frame rates.

For preventing AI behaviour, damage-dealing, and/or trap damage-dealing:
    - Don't just check against time; but perhaps record and check against frame count (in case computer is lagging)

Various checks are used in other classes already; need to improve, adjust, call where necessary:
- `Game.CanPlayMinorSoundEffects`
- `DungeonRoomTransitioner.IsLoadingOrRevealingRoom`
- `DungeonRoomTransitioner.EnemiesCanMove`
- `DungeonRoomTransitioner.CreaturesCanReceiveDamage` 
- `CreatureStruct.ReceiveDamage`

`CreaturesCanReceiveDamage` checks against `bool ProjectilesCanUpdate`, which checks against:

```csharp
if (state == DungeonRoomTransitionerState.RevealingRoom) {
	return timer.PercentageDone >= .1f;
}
```

... Wonder if there's a race condition where, if computer is lagging, physics update from a trap is lagging behind from where a trap was instantiated during the room load, since `.1f` is a short amount.

Flails do not deal damage to kittens (neither from player nor enemies), and explosions shouldn't reach that far.

`Trap_ElementalSpinner.OnInstantiated` instantiates its balls @ runtime, though the balls' colliders are disabled initially.
Though, each ball has `TrapBall.positionLastFrame` – perhaps its previous frame was set from the room center, and it seems `Trap_ElementalSpinner` performs `Physics2D.CircleCastNonAlloc` from `ball.positionLastFrame` to the current position, so perhaps each ball is sweeping from bad positions due to low frame rates during loading, and happened to hit the kitten (which generally have very low health)?

Grasping at straws without a combat log though.

**Comment by ChrisNZL** [comment]
Further report:

>On the 10th floor I went into a waypoint, when I came back out, most of the enemies on the floor below were dead, including the enemy in the kitten chamber. A couple were still alive. I have no idea what killed them, there's no saw traps that would do it.

Also wondering if enemy MaxHealth is `0` due to AlterantTracker rebuilding too slowly, or a frame too late or something.

**Comment by ChrisNZL** [comment]
Adding a check within `CreatureStruct.ReceiveDamage` to return early if `MaxHealth <= 0`, in case AlterantTracker hasn't recalculated fast enough due to a frame time issue.

**Comment by ChrisNZL** [comment]
Hoping the MaxHealth check is enough for v0.3.0... Will re-open this later if needed.

**Comment by ChrisNZL** [comment]
Re-opening. Report from 0.3.0a; this issue is still happening. Mob guarding kitten dies somehow.

![image](https://user-images.githubusercontent.com/280814/147898325-704f0fd1-3f49-4cee-94f4-b9e10e97e8cc.png)

**Comment by ChrisNZL** [comment]
This should be fixed now in v0.3.1a.

Fixed issues with the following objects where previous-frame-positions were not reset between room transitions, causing collision checks to be grossly incorrect during the first frame after a room was loaded:

- Bloat giblets
- Elemental Spinner Traps
- Flail
- Leaf Shield
