### ISSUE TITLE
Server does not Vacuum GameStruct data before sending to clients, causing NetID clashes

### ISSUE THREAD

**Issue by ChrisNZL** [ChrisNZL/Tallowmere2#999]
Auto report, 0.3.2a, feedback ID 20220202-LD2ZS

Error title should technically be:
```
Null ref: T2.DungeonRoomObject_TreasureChest.GetInteractableActionStringForCreature
```

But, with the newly-added logging, I believe this log holds enough info to properly resolve issues:
- [Online Co-op / Null ref: T2.DungeonRoom.Update #986](https://github.com/ChrisNZL/Tallowmere2/issues/986)
- [Online Co-op error: Desire_EnterCorridor: Failed to get objectStruct. #991](https://github.com/ChrisNZL/Tallowmere2/issues/991)

Log shows many warnings of objects, items, and creatures that belonged to a room ~10 rooms prior... which is what the server would have Vaccumed during a cleanup method when creating a new room.

I suspect the NetIDs were then regurgitated server-side (and handled by the server), but the local client has not received any information about what to vacuum, thus the server is sending NetIDs that the client is clashing with.

### 💡 Also looks possible that there is an issue with:
1. Client tells server: client wants to resume a previous online co-op game.
2. Server sends full GameStruct data to client WITHOUT VACUUMING, and client imports all GameStruct data (which can include old rooms and objects.
3. Server Vacuums old objects and NetIDs (when the next room is generated I believe).
4. Thus, NetIDs that get Vacuumed and recycled in the session server-side – the client never actually vacuums such NetIDs. Thus client has clashing NetIDs because it was never told (nor figured out), which NetIDs to vacuum.

So this might be an issue when resuming an online co-op game more than anything
- Yes, two other logs... One being Feedback ID 0.3.0a_20211226-F24JG
 - Player was playing online, new game, few rooms no issues.
 - Player disconnected, then loaded a _different_ online co-op game to resume,
   - Player encountered warnings and errors with NetIDs and objects not found / in use...
     - Sounds like issue with loading/resuming online co-op games and NetIDs being Vacuumed server-side but not getting Vacuumed client-side, thus clashes happen.

### Tasks TODO:
- [ ] Log server-side which objects and NetIDs are getting deleted
- [ ] Deduce if NetIDs are being recycled and re-used server-side in a single session
- [ ] Ensure client is vacuuming the same NetIDs, _and/or_ ensure server does not send recycled NetIDs in a single session

### ⚠ These are probably the most important tasks:
- [ ] Force Server to Vacuum the GameStruct before sending to client when loading/resuming a game.
- [ ] Let server and client communicate how many NetIDs/objects are in use... Force a resync if amounts don't match.

---

## Log part 1

```
4:56:19, Frame 55347, LOG »  NetworkMessage_DungeonRoomTransitionHelper:
Desire_EnterWaypoint: Entering waypoint...

4:56:20, Frame 55383, LOG »  DungeonRoomTransitioner.BeginTransitioningToRoom: Departing Room 0, going to Room 28...

4:56:21, Frame 55433, LOG »  NetworkMessage_DungeonRoomTransitionHelper: Received message.
Desire: 4 » BeginLoadingRoom


4:56:21, Frame 55433, LOG »  NetworkMessage_DungeonRoomTransitionHelper: case Desire_BeginLoadingRoom: Received fractionBlob. Importing...
blob.roomStruct.RoomNumber: 28
blob.homeMerchantRefreshedStock: True
blob.creatureStructs.Count: 2
blob.objectStructs.Count: 60
blob.itemStructs.Count: 59
blob.creaturePositions.Count: 0
blob.gibStructs.Count: 1
blob.kittenShelfStructChanges.Count: 0


4:56:21, Frame 55433, LOG »  ImportRoomBlob results:
insertedRoom: False
Home merchant: totalItemsRemovedFromIDDB: 16
totalCreaturesInserted: 0
totalObjectsInserted: 0
totalItemsInserted: 16
totalGibStructsAdded: 0
totalKittenShelfChanges: 0



4:56:21, Frame 55477, LOG »  NetworkMessage_DungeonRoomTransitionHelper: Received message.
Desire: 6 » RevealRoom

4:56:21, Frame 55478, LOG »  DungeonRoomTransitioner.Update: Revealing room: 第28个房间：墓地 (Room 28)

4:56:40, Frame 56589, LOG »  NetworkMessage_DungeonRoomTransitionHelper: Received message.
Desire: 1 » EnterCorridor


4:56:40, Frame 56589, LOG »  NetworkMessage_DungeonRoomTransitionHelper:
Desire_EnterCorridor: Entering corridor...

4:56:40, Frame 56589, LOG »  DungeonRoomTransitioner.BeginTransitioningToRoom: Departing Room 28, going to Room 29...

4:56:41, Frame 56639, LOG »  NetworkMessage_SubmitLeaderboardEntries: Received numbers to submit.
highestRoomNumberReached: 29
seconds: 4711

4:56:41, Frame 56639, LOG »  NetworkMessage_SetDoorState: Closing door. doorStructNetID Master5. doorState Closed. RoomNumber 0
4:56:41, Frame 56639, LOG »  NetworkMessage_SetDoorState: Closing door. doorStructNetID Master1286. doorState Closed. RoomNumber 19
4:56:41, Frame 56639, LOG »  NetworkMessage_SetDoorState: Closing door. doorStructNetID Master5. doorState Closed. RoomNumber 0

4:56:41, Frame 56639, LOG »  NetworkMessage_DungeonRoomTransitionHelper: Received message.
Desire: 4 » BeginLoadingRoom


4:56:41, Frame 56639, LOG »  NetworkMessage_DungeonRoomTransitionHelper: case Desire_BeginLoadingRoom: Received fractionBlob. Importing...
blob.roomStruct.RoomNumber: 29
blob.homeMerchantRefreshedStock: True
blob.creatureStructs.Count: 39
blob.objectStructs.Count: 34
blob.itemStructs.Count: 97
blob.creaturePositions.Count: 0
blob.gibStructs.Count: 0
blob.kittenShelfStructChanges.Count: 0


4:56:41, Frame 56639, WARNING »  WARNING: NetIDDatabase.InsertInventoryItemStruct: CLASH: A struct has already been inserted with netID Master764
Type: WaypointStruct. DungeonRoomObjectID: Waypoint. Parent room: (NetID: Master761. RoomNumber: 14)


4:56:41, Frame 56639, WARNING »  WARNING: NetIDDatabase.InsertInventoryItemStruct: CLASH: A struct has already been inserted with netID Master762
Type: CorridorStruct. DungeonRoomObjectID: CorridorWest. Parent room: (NetID: Master761. RoomNumber: 14)


4:56:41, Frame 56639, WARNING »  WARNING: NetIDDatabase.InsertInventoryItemStruct: CLASH: A struct has already been inserted with netID Master768
Type: DungeonRoomObjectStruct_TreasureChest. DungeonRoomObjectID: TreasureChest. Parent room: (NetID: Master761. RoomNumber: 14)


4:56:41, Frame 56639, WARNING »  WARNING: NetIDDatabase.InsertInventoryItemStruct: CLASH: A struct has already been inserted with netID Master774
Type: DungeonRoomObjectStruct_TreasureChest. DungeonRoomObjectID: TreasureChest. Parent room: (NetID: Master761. RoomNumber: 14)


4:56:41, Frame 56639, WARNING »  WARNING: NetIDDatabase.InsertInventoryItemStruct: CLASH: A struct has already been inserted with netID Master772
Type: DungeonRoomObjectStruct_TreasureChest. DungeonRoomObjectID: TreasureChest. Parent room: (NetID: Master761. RoomNumber: 14)


4:56:41, Frame 56639, WARNING »  WARNING: NetIDDatabase.InsertInventoryItemStruct: CLASH: A struct has already been inserted with netID Master763
Type: CorridorStruct. DungeonRoomObjectID: CorridorEast. Parent room: (NetID: Master761. RoomNumber: 14)


4:56:41, Frame 56639, WARNING »  WARNING: NetIDDatabase.InsertInventoryItemStruct: CLASH: A struct has already been inserted with netID Master766
Type: DungeonRoomObjectStruct_TreasureChest. DungeonRoomObjectID: TreasureChest. Parent room: (NetID: Master761. RoomNumber: 14)


4:56:41, Frame 56639, WARNING »  WARNING: NetIDDatabase.InsertInventoryItemStruct: CLASH: A struct has already been inserted with netID Master770
Type: DungeonRoomObjectStruct_TreasureChest. DungeonRoomObjectID: TreasureChest. Parent room: (NetID: Master761. RoomNumber: 14)


4:56:41, Frame 56639, WARNING »  WARNING: NetIDDatabase.InsertInventoryItemStruct: CLASH: A struct has already been inserted with netID Master798
Type: DungeonRoomObjectStruct_Door. DungeonRoomObjectID: Door. Parent room: (NetID: Master761. RoomNumber: 14)


4:56:41, Frame 56639, WARNING »  WARNING: NetIDDatabase.InsertInventoryItemStruct: CLASH: A struct has already been inserted with netID Master799
Type: DungeonRoomObjectStruct_Door. DungeonRoomObjectID: Door. Parent room: (NetID: Master761. RoomNumber: 14)


4:56:41, Frame 56639, WARNING »  WARNING: NetIDDatabase.InsertInventoryItemStruct: CLASH: A struct has already been inserted with netID Master802
Type: TrapStruct. DungeonRoomObjectID: Trap_LightningTrap. Parent room: (NetID: Master761. RoomNumber: 14)


4:56:41, Frame 56639, WARNING »  WARNING: NetIDDatabase.InsertInventoryItemStruct: CLASH: A struct has already been inserted with netID Master800
Type: DungeonRoomObjectStruct. DungeonRoomObjectID: DemonStatue. Parent room: (NetID: Master761. RoomNumber: 14)


4:56:41, Frame 56639, WARNING »  WARNING: NetIDDatabase.InsertInventoryItemStruct: CLASH: A struct has already been inserted with netID Master801
Type: TrapStruct. DungeonRoomObjectID: Trap_Spikes. Parent room: (NetID: Master761. RoomNumber: 14)


4:56:41, Frame 56639, WARNING »  WARNING: NetIDDatabase.InsertInventoryItemStruct: CLASH: A struct has already been inserted with netID Master804
Type: TrapStruct. DungeonRoomObjectID: Trap_Spikes. Parent room: (NetID: Master761. RoomNumber: 14)


4:56:41, Frame 56639, WARNING »  WARNING: NetIDDatabase.InsertInventoryItemStruct: CLASH: A struct has already been inserted with netID Master803
Type: TrapStruct. DungeonRoomObjectID: Trap_Spikes. Parent room: (NetID: Master761. RoomNumber: 14)


4:56:41, Frame 56639, WARNING »  WARNING: NetIDDatabase.InsertInventoryItemStruct: CLASH: A struct has already been inserted with netID Master805
Type: TrapStruct. DungeonRoomObjectID: Trap_Spikes. Parent room: (NetID: Master761. RoomNumber: 14)


4:56:41, Frame 56639, WARNING »  WARNING: NetIDDatabase.InsertInventoryItemStruct: CLASH: A struct has already been inserted with netID Master807
Type: TrapStruct. DungeonRoomObjectID: Trap_Spikes. Parent room: (NetID: Master761. RoomNumber: 14)


4:56:41, Frame 56639, WARNING »  WARNING: NetIDDatabase.InsertInventoryItemStruct: CLASH: A struct has already been inserted with netID Master808
Type: TrapStruct. DungeonRoomObjectID: Trap_LightningTrap. Parent room: (NetID: Master761. RoomNumber: 14)


4:56:41, Frame 56639, WARNING »  WARNING: NetIDDatabase.InsertInventoryItemStruct: CLASH: A struct has already been inserted with netID Master806
Type: TrapStruct. DungeonRoomObjectID: Trap_Pinwheel. Parent room: (NetID: Master761. RoomNumber: 14)


4:56:41, Frame 56639, LOG »  ImportRoomBlob results:
insertedRoom: True
Home merchant: totalItemsRemovedFromIDDB: 16
totalCreaturesInserted: 37
totalObjectsInserted: 34
totalItemsInserted: 39
totalGibStructsAdded: 0
totalKittenShelfChanges: 0


4:56:41, Frame 56652, WARNING »  WARNING: Creature.InstantiateAndHoldInventoryItemFromItemStruct: itemStruct is null. creatureStruct.netID: Master702
4:56:41, Frame 56652, WARNING »  WARNING: Creature.InstantiateAndHoldInventoryItemFromItemStruct: itemStruct is null. creatureStruct.netID: Master703
4:56:41, Frame 56652, WARNING »  WARNING: Creature.InstantiateAndHoldInventoryItemFromItemStruct: itemStruct is null. creatureStruct.netID: Master709
4:56:41, Frame 56652, WARNING »  WARNING: Creature.InstantiateAndHoldInventoryItemFromItemStruct: itemStruct is null. creatureStruct.netID: Master710
4:56:41, Frame 56652, WARNING »  WARNING: Creature.InstantiateAndHoldInventoryItemFromItemStruct: itemStruct is null. creatureStruct.netID: Master712
4:56:41, Frame 56652, WARNING »  WARNING: Creature.InstantiateAndHoldInventoryItemFromItemStruct: itemStruct is null. creatureStruct.netID: Master704
4:56:41, Frame 56652, WARNING »  WARNING: Creature.InstantiateAndHoldInventoryItemFromItemStruct: itemStruct is null. creatureStruct.netID: Master706
4:56:41, Frame 56652, WARNING »  WARNING: Creature.InstantiateAndHoldInventoryItemFromItemStruct: itemStruct is null. creatureStruct.netID: Master707

4:56:42, Frame 56674, LOG »  NetworkMessage_DungeonRoomTransitionHelper: Received message.
Desire: 6 » RevealRoom

4:56:42, Frame 56675, LOG »  DungeonRoomTransitioner.Update: Revealing room: 第29个房间：墓地 (Room 29)

4:57:55, Frame 61004, WARNING »  WARNING: NetIDDatabase.InsertGibStruct: gibStructs already contains key for NetID Master809
CLASH: A struct has already been inserted with netID Master809
Type: TrapStruct. DungeonRoomObjectID: Trap_FireTrap. Parent room: (NetID: Master761. RoomNumber: 14)
```

## Log part 2

```
5:17:24, Frame 129548, LOG »  DungeonRoomTransitioner.Update: Revealing room: 第33个房间：圣堂 (Room 33)
5:17:51, Frame 131168, LOG »  PotionBehaviour.OnConsumePotion: Telling server to make creature drink potion. simpleItemStruct.netID: Master1728
5:18:42, Frame 134245, LOG »  Player 狗蛋 has fallen!
5:19:33, Frame 137251, LOG »  Player 狗蛋 has been revived.
5:21:30, Frame 144247, LOG »  Player 狗蛋 has fallen!
5:22:23, Frame 147357, LOG »  Player 狗蛋 has been revived.
5:22:54, Frame 149247, LOG »  PotionBehaviour.OnConsumePotion: Telling server to make creature drink potion. simpleItemStruct.netID: Master55

5:23:15, Frame 150515, LOG »  NetworkMessage_DungeonRoomTransitionHelper: Received message.
Desire: 1 » EnterCorridor


5:23:15, Frame 150515, LOG »  NetworkMessage_DungeonRoomTransitionHelper:
Desire_EnterCorridor: Entering corridor...

5:23:15, Frame 150515, LOG »  DungeonRoomTransitioner.BeginTransitioningToRoom: Departing Room 33, going to Room 34...

5:23:16, Frame 150564, LOG »  NetworkMessage_SubmitLeaderboardEntries: Received numbers to submit.
highestRoomNumberReached: 34
seconds: 6307

5:23:16, Frame 150564, LOG »  NetworkMessage_SetDoorState: Closing door. doorStructNetID Master5. doorState Closed. RoomNumber 0
5:23:16, Frame 150564, LOG »  NetworkMessage_SetDoorState: Closing door. doorStructNetID Master1872. doorState Closed. RoomNumber 24
5:23:16, Frame 150564, LOG »  NetworkMessage_SetDoorState: Closing door. doorStructNetID Master5. doorState Closed. RoomNumber 0

5:23:16, Frame 150564, LOG »  NetworkMessage_DungeonRoomTransitionHelper: Received message.
Desire: 4 » BeginLoadingRoom


5:23:16, Frame 150564, LOG »  NetworkMessage_DungeonRoomTransitionHelper: case Desire_BeginLoadingRoom: Received fractionBlob. Importing...
blob.roomStruct.RoomNumber: 34
blob.homeMerchantRefreshedStock: True
blob.creatureStructs.Count: 91
blob.objectStructs.Count: 51
blob.itemStructs.Count: 175
blob.creaturePositions.Count: 0
blob.gibStructs.Count: 0
blob.kittenShelfStructChanges.Count: 0


5:23:16, Frame 150564, WARNING »  WARNING: NetIDDatabase.InsertCreatureStruct: CLASH: A struct has already been inserted with netID Master1617
Type: DungeonRoomObjectStruct_TreasureChest. DungeonRoomObjectID: TreasureChest. Parent room: (NetID: Master1598. RoomNumber: 22)


5:23:16, Frame 150564, WARNING »  WARNING: NetIDDatabase.InsertCreatureStruct: CLASH: A struct has already been inserted with netID Master1649
Type: DungeonRoomObjectStruct_Door. DungeonRoomObjectID: Door. Parent room: (NetID: Master1598. RoomNumber: 22)


5:23:16, Frame 150564, WARNING »  WARNING: NetIDDatabase.InsertCreatureStruct: CLASH: A struct has already been inserted with netID Master1650
Type: DungeonRoomObjectStruct. DungeonRoomObjectID: DemonStatue. Parent room: (NetID: Master1598. RoomNumber: 22)


5:23:16, Frame 150564, WARNING »  WARNING: NetIDDatabase.InsertCreatureStruct: CLASH: A struct has already been inserted with netID Master1619
Type: DungeonRoomObjectStruct_TreasureChest. DungeonRoomObjectID: TreasureChest. Parent room: (NetID: Master1598. RoomNumber: 22)


5:23:16, Frame 150564, WARNING »  WARNING: NetIDDatabase.InsertCreatureStruct: CLASH: A struct has already been inserted with netID Master1661
Type: DungeonRoomObjectStruct. DungeonRoomObjectID: SpawnPoint. Parent room: (NetID: Master1598. RoomNumber: 22)


5:23:16, Frame 150564, WARNING »  WARNING: NetIDDatabase.InsertCreatureStruct: CLASH: A struct has already been inserted with netID Master1658
Type: TrapStruct. DungeonRoomObjectID: Trap_Spikes. Parent room: (NetID: Master1598. RoomNumber: 22)


5:23:16, Frame 150564, WARNING »  WARNING: NetIDDatabase.InsertCreatureStruct: CLASH: A struct has already been inserted with netID Master1651
Type: TrapStruct. DungeonRoomObjectID: Trap_Pinwheel. Parent room: (NetID: Master1598. RoomNumber: 22)


5:23:16, Frame 150564, WARNING »  WARNING: NetIDDatabase.InsertCreatureStruct: CLASH: A struct has already been inserted with netID Master1611
Type: DungeonRoomObjectStruct_TreasureChest. DungeonRoomObjectID: TreasureChest. Parent room: (NetID: Master1598. RoomNumber: 22)


5:23:16, Frame 150564, WARNING »  WARNING: NetIDDatabase.InsertCreatureStruct: CLASH: A struct has already been inserted with netID Master1657
Type: TrapStruct. DungeonRoomObjectID: Trap_Pinwheel. Parent room: (NetID: Master1598. RoomNumber: 22)


5:23:16, Frame 150564, WARNING »  WARNING: NetIDDatabase.InsertCreatureStruct: CLASH: A struct has already been inserted with netID Master1615
Type: DungeonRoomObjectStruct_TreasureChest. DungeonRoomObjectID: TreasureChest. Parent room: (NetID: Master1598. RoomNumber: 22)


5:23:16, Frame 150564, WARNING »  WARNING: NetIDDatabase.InsertCreatureStruct: CLASH: A struct has already been inserted with netID Master1654
Type: TrapStruct. DungeonRoomObjectID: Trap_Spikes. Parent room: (NetID: Master1598. RoomNumber: 22)


5:23:16, Frame 150564, WARNING »  WARNING: NetIDDatabase.InsertCreatureStruct: CLASH: A struct has already been inserted with netID Master1652
Type: TrapStruct. DungeonRoomObjectID: Trap_Spikes. Parent room: (NetID: Master1598. RoomNumber: 22)


5:23:16, Frame 150564, WARNING »  WARNING: NetIDDatabase.InsertCreatureStruct: CLASH: A struct has already been inserted with netID Master1613
Type: DungeonRoomObjectStruct_TreasureChest. DungeonRoomObjectID: TreasureChest. Parent room: (NetID: Master1598. RoomNumber: 22)


5:23:16, Frame 150564, WARNING »  WARNING: NetIDDatabase.InsertCreatureStruct: CLASH: A struct has already been inserted with netID Master1660
Type: TrapStruct. DungeonRoomObjectID: Trap_Pinwheel. Parent room: (NetID: Master1598. RoomNumber: 22)


5:23:16, Frame 150564, WARNING »  WARNING: NetIDDatabase.InsertCreatureStruct: CLASH: A struct has already been inserted with netID Master1659
Type: TrapStruct. DungeonRoomObjectID: Trap_Spikes. Parent room: (NetID: Master1598. RoomNumber: 22)


5:23:16, Frame 150564, WARNING »  WARNING: NetIDDatabase.InsertCreatureStruct: CLASH: A struct has already been inserted with netID Master1609
Type: DungeonRoomObjectStruct_TreasureChest. DungeonRoomObjectID: TreasureChest. Parent room: (NetID: Master1598. RoomNumber: 22)


5:23:16, Frame 150564, WARNING »  WARNING: NetIDDatabase.InsertCreatureStruct: CLASH: A struct has already been inserted with netID Master1653
Type: TrapStruct. DungeonRoomObjectID: Trap_FireTrap. Parent room: (NetID: Master1598. RoomNumber: 22)


5:23:16, Frame 150564, WARNING »  WARNING: NetIDDatabase.InsertCreatureStruct: CLASH: A struct has already been inserted with netID Master1655
Type: TrapStruct. DungeonRoomObjectID: Trap_Spikes. Parent room: (NetID: Master1598. RoomNumber: 22)


5:23:16, Frame 150564, WARNING »  WARNING: NetIDDatabase.InsertCreatureStruct: CLASH: A struct has already been inserted with netID Master1648
Type: DungeonRoomObjectStruct_Door. DungeonRoomObjectID: Door. Parent room: (NetID: Master1598. RoomNumber: 22)


5:23:16, Frame 150564, WARNING »  WARNING: NetIDDatabase.InsertCreatureStruct: CLASH: A struct has already been inserted with netID Master1656
Type: TrapStruct. DungeonRoomObjectID: Trap_Pinwheel. Parent room: (NetID: Master1598. RoomNumber: 22)


5:23:16, Frame 150564, WARNING »  WARNING: NetIDDatabase.InsertDungeonRoomObjectStruct: CLASH: A struct has already been inserted with netID Master1607
Type: DungeonRoomObjectStruct_TreasureChest. DungeonRoomObjectID: TreasureChest. Parent room: (NetID: Master1598. RoomNumber: 22)


5:23:16, Frame 150564, WARNING »  WARNING: NetIDDatabase.InsertDungeonRoomObjectStruct: CLASH: A struct has already been inserted with netID Master1600
Type: CorridorStruct. DungeonRoomObjectID: CorridorEast. Parent room: (NetID: Master1598. RoomNumber: 22)


5:23:16, Frame 150564, WARNING »  WARNING: NetIDDatabase.InsertInventoryItemStruct: CLASH: A struct has already been inserted with netID Master1605
Type: DungeonRoomObjectStruct_TreasureChest. DungeonRoomObjectID: TreasureChest. Parent room: (NetID: Master1598. RoomNumber: 22)


5:23:16, Frame 150564, WARNING »  WARNING: NetIDDatabase.InsertInventoryItemStruct: CLASH: A struct has already been inserted with netID Master1603
Type: DungeonRoomObjectStruct_TreasureChest. DungeonRoomObjectID: TreasureChest. Parent room: (NetID: Master1598. RoomNumber: 22)


5:23:16, Frame 150564, WARNING »  WARNING: NetIDDatabase.InsertInventoryItemStruct: CLASH: A struct has already been inserted with netID Master1601
Type: WaypointStruct. DungeonRoomObjectID: Waypoint. Parent room: (NetID: Master1598. RoomNumber: 22)


5:23:16, Frame 150564, WARNING »  WARNING: NetIDDatabase.InsertInventoryItemStruct: CLASH: A struct has already been inserted with netID Master1599
Type: CorridorStruct. DungeonRoomObjectID: CorridorWest. Parent room: (NetID: Master1598. RoomNumber: 22)


5:23:16, Frame 150564, LOG »  ImportRoomBlob results:
insertedRoom: True
Home merchant: totalItemsRemovedFromIDDB: 11
totalCreaturesInserted: 69
totalObjectsInserted: 49
totalItemsInserted: 108
totalGibStructsAdded: 0
totalKittenShelfChanges: 0


5:23:17, Frame 150570, WARNING »  WARNING: DungeonRoomObject_TreasureChest.InstantiateFakeObject: itemStruct is null
[[[ ^ REPEATING MESSAGE... ]]]


5:23:18, Frame 150638, LOG »  NetworkMessage_DungeonRoomTransitionHelper: Received message.
Desire: 6 » RevealRoom

5:23:18, Frame 150639, LOG »  DungeonRoomTransitioner.Update: Revealing room: 第34个房间：圣堂 (Room 34)


5:24:59, Frame 156418, EXCEPTION »  NullReferenceException: Object reference not set to an instance of an object
>>>>> CRITICAL ERROR >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

T2.DungeonRoomObject_TreasureChest.GetInteractableActionStringForCreature (T2.Creature creature)
T2.Interactable.GetActionStringForCreature (T2.Creature creature)
T2.Tooltip.SetTooltipTextForInteractable (T2.Creature creature)
T2.HUD_Singleplayer.SetInteractable (T2.Creature creature, System.Boolean forceUpdateTextForChest)
T2.CreatureBody.LateUpdate ()

GameStates: RompingThroughDungeon
OnlineGameInfo: Device is online.
Server: Lightning-Beijing-01
GameID: MPHXB
GameSetupMode: NetworkCoop
Players: 2
DungeonRoomTransitioner.state: Null
DungeonRoom.state: Ready
Room: 34 / 34
RoomModifiers: DoubleTrouble (双倍麻烦), LargeRoom (大型房间), ExtraAttacks (攻击次数增加), Tilted (歪歪斜斜), BowsOnly (弓箭练习)
YouHaveDiedState: Null
SystemPlayer InputDevice: 键盘
HumanPlayer 1 InputDevice: 键盘
```

**Comment by ChrisNZL** [comment]
Fixed in 0.3.3.

Server now tells clients which things to remove via `NetworkMessage_Vacuum`.
